// seed.js - Script untuk menambahkan data sejarah ke database
const mongoose = require('mongoose');
const koneksiDatabase = require('./config/database');
const Sejarah = require('./models/sejarah');

async function tambahDataSejarah() {
  try {
    // Koneksi ke database
    await koneksiDatabase();
    
    // Data sejarah yang akan ditambahkan
    const dataSejarah = [
      {
        judul_sejarah: "Perang Dunia Pertama",
        deskripsi_sejarah: "Perang Dunia Pertama (1914-1918) adalah konflik global besar antara Blok Sekutu (Inggris, Perancis, Rusia, Amerika) dan Blok Sentral (Jerman, Austria-Hungaria, Ottoman). Perang ini dimulai dengan pembunuhan Archduke Franz Ferdinand dan berkembang menjadi perang total. Menghasilkan jutaan korban, perubahan peta politik Eropa, dan perlucutan senjata Jerman.",
        periode: "1914-1918",
        kata_kunci: "perang, dunia, pertama, besar",
        wilayah: "Eropa, Timur Tengah, Afrika",
        tokoh_penting: ["Kaiser Wilhelm II", "Tsar Nicholas II", "Winston Churchill", "Georges Clemenceau"],
        dampak: "Pembentukan Liga Bangsa-Bangsa, perubahan peta Eropa, kehancuran empires Austria-Hungaria dan Ottoman",
        penyebab: "Sistem aliansi kompleks, persaingan kolonial, perlombaan senjata, nasionalisme ekstrem",
        akibat: "20 juta korban, ekonomi Eropa hancur, treaty Versailles yang keras, gesekan untuk Perang Dunia II",
        sumber_referensi: ["The Great War: World War I", "1914-1918 The History of World War One"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Perang Dunia Kedua",
        deskripsi_sejarah: "Perang Dunia Kedua (1939-1945) adalah perang paling mematikan dalam sejarah manusia dengan estimasi 70-85 juta korban jiwa. Dimulai dengan invasi Nazi Jerman ke Polandia dan berkembang melibatkan mayoritas negara di dunia. Perang ini diwarnai dengan Holocaust (pembunuhan sistematis 6 juta Yahudi) dan pengembangan senjata nuklir.",
        periode: "1939-1945",
        kata_kunci: "perang, dunia, kedua, holocaust",
        wilayah: "Eropa, Asia, Afrika, Pasifik",
        tokoh_penting: ["Adolf Hitler", "Winston Churchill", "Franklin D. Roosevelt", "Joseph Stalin", "Emperor Hirohito"],
        dampak: "Pembentukan PBB, Perang Dingin dimulai, Jepang dan Jerman diduduki, nuklir era dimulai, dekolonisasi",
        penyebab: "Perlakuan keras Treaty Versailles, depresi ekonomi, fascisme, militarisme Jepang, isolasionisme",
        akibat: "75 juta korban, Holocaust, pembom nuklir Hiroshima-Nagasaki, divisi dunia menjadi dua blok",
        sumber_referensi: ["The Second World War by Winston Churchill", "World War II: The Definitive Illustrated History"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Revolusi Perancis",
        deskripsi_sejarah: "Revolusi Perancis (1789-1799) adalah peristiwa penting yang mengubah struktur sosial Eropa secara fundamental. Dipicu oleh krisis ekonomi, ketidakpuasan sosial, dan ide-ide pencerahan. Revolusi ini menghasilkan Deklarasi Hak Asasi Manusia yang menekankan kebebasan, kesetaraan, dan keadilan.",
        periode: "1789-1799",
        kata_kunci: "revolusi, perancis, demokrasi, hak asasi",
        wilayah: "Perancis, Eropa",
        tokoh_penting: ["Louis XVI", "Marie Antoinette", "Robespierre", "Napoleon Bonaparte", "Lafayette"],
        dampak: "Penghapusan sistem feodal, ideologi liberal dan demokratis, inspirasi revolusi di seluruh dunia",
        penyebab: "Krisis keuangan, kelaparan, hutang negara, ketidakpuasan Tiers Etat, ide Pencerahan",
        akibat: "Deklarasi Hak Asasi Manusia, Konstitusi Perancis, Periode Teror, naik turunnya Napoleon",
        sumber_referensi: ["A Tale of Two Cities", "Citizens by Simon Schama"],
        kategori: "Revolusi"
      },
      {
        judul_sejarah: "Revolusi Industri",
        deskripsi_sejarah: "Revolusi Industri (1760-1840) adalah transformasi besar dalam cara produksi manusia dari manufaktur manual menjadi mesin otomatis. Dimulai di Inggris dengan penemuan mesin uap James Watt dan berkembang ke tekstil, baja, dan pertambangan.",
        periode: "1760-1840",
        kata_kunci: "revolusi, industri, teknologi, mesin",
        wilayah: "Inggris, Eropa Barat, Amerika",
        tokoh_penting: ["James Watt", "George Stephenson", "Richard Arkwright", "Henry Ford"],
        dampak: "Pembentukan kapitalisme modern, urbanisasi, kelas pekerja, teknologi transportasi, ekspansi kolonial",
        penyebab: "Penemuan mesin uap, ketersediaan modal, sumber daya alam, pasar yang berkembang",
        akibat: "Produksi massal, pabrik besar, migrasi dari desa ke kota, polusi industri, kesenjangan sosial",
        sumber_referensi: ["The Industrial Revolution", "Engines of Change by Peter Tomlinson"],
        kategori: "Revolusi Teknologi"
      },
      {
        judul_sejarah: "Kerajaan Romawi",
        deskripsi_sejarah: "Kerajaan Romawi (27 SM - 476 M) adalah salah satu peradaban terbesar dalam sejarah yang mendominasi dunia Barat selama lima abad. Didirikan oleh Oktavianus (Augustus) setelah Perang Sipil, kerajaan ini menciptakan stabilitas, kemakmuran, dan inovasi budaya.",
        periode: "27 SM - 476 M",
        kata_kunci: "romawi, kuno, kerajaan, caesar",
        wilayah: "Mediterania, Eropa, Timur Tengah, Afrika Utara",
        tokoh_penting: ["Augustus", "Julius Caesar", "Marcus Aurelius", "Hadrian", "Constantine"],
        dampak: "Hukum Romawi masih digunakan, Latin menjadi akar bahasa Eropa, arsitektur klasik, Kristianitas berkembang",
        penyebab: "Republik Romawi yang lemah, ambisius pemimpin, kebutuhan stabilitas",
        akibat: "Stabilitas 500 tahun, penyebaran budaya Romawi, jatuhnya membuka Abad Pertengahan",
        sumber_referensi: ["The History of Rome", "SPQR by Mary Beard"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Peradaban Mesir Kuno",
        deskripsi_sejarah: "Peradaban Mesir Kuno (3100 SM - 30 SM) adalah salah satu peradaban tertua dan paling berpengaruh di dunia, berlangsung lebih dari 3000 tahun. Terletak di Sungai Nil, peradaban ini mengembangkan sistem irigasi canggih, hieroglif, dan arsitektur megah seperti piramida.",
        periode: "3100 SM - 30 SM",
        kata_kunci: "mesir, kuno, piramida, firaun",
        wilayah: "Mesir, Sungai Nil",
        tokoh_penting: ["Khufu", "Ramesses II", "Hatshepsut", "Thutmose III", "Cleopatra VII"],
        dampak: "Sistem penulisan hieroglif, arsitektur monumental, matematika dan astronomi maju, agama berpengaruh",
        penyebab: "Posisi geografis Sungai Nil, sistem pertanian yang stabil, kepemimpinan berpusat",
        akibat: "Warisan budaya yang bertahan ribuan tahun, monumen ikonis, pengetahuan ilmiah maju",
        sumber_referensi: ["Ancient Egypt: The Definitive Illustrated History", "The Oxford History of Ancient Egypt"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Dinasti Ming",
        deskripsi_sejarah: "Dinasti Ming (1368-1644) adalah dinasti terakhir Tiongkok yang diperintah oleh etnis Han, menggantikan Dinasti Yuan yang dipimpin Mongol. Dinasti Ming menciptakan periode keemasan dengan pembangunan Tembok Besar (konstruksi ulang), Kota Terlarang (istana kekaisaran), dan kemajuan dalam keramik, porselain, dan seni.",
        periode: "1368-1644",
        kata_kunci: "dinasti, ming, tiongkok, tembok, besar",
        wilayah: "Cina, Asia Timur, Asia Tenggara, Samudera Hindia",
        tokoh_penting: ["Zhu Yuanzhang", "Yongle", "Zheng He", "Kangxi"],
        dampak: "Tembok Besar Cina modern, porcelain berkualitas tinggi, eksplorasi maritim, seni dan sastra berkembang",
        penyebab: "Penggulingan Dinasti Yuan, keinginan untuk stabilitas dan kebesaran, ekspansi kekuasaan",
        akibat: "Periode emas budaya Cina, tetapi ekonomi tertutup membuat Cina tertinggal dari Barat",
        sumber_referensi: ["The Ming Dynasty", "1434: The Year a Magnificent Chinese Fleet Sailed West"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Era Renaissance",
        deskripsi_sejarah: "Era Renaissance (1300-1600) adalah periode kebangkitan seni, sastra, ilmu pengetahuan, dan humanism di Eropa, menandai transisi dari Abad Pertengahan ke era modern. Dimulai di Italia dengan kembangnya minat terhadap karya Yunani dan Romawi klasik, renaissance menyebarkan semangat inovasi dan eksplorasi intelektual.",
        periode: "1300-1600",
        kata_kunci: "renaissance, seni, budaya, humanisme",
        wilayah: "Italia, Eropa",
        tokoh_penting: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Dante Alighieri", "Petrarch"],
        dampak: "Kebangkitan seni dan budaya, fondasi sains modern, pelindung seni dan pembelajaran",
        penyebab: "Kembangnya minat pada klasik Yunani-Romawi, pertumbuhan perdagangan, kekayaan merchant",
        akibat: "Transformasi seni Eropa, perkembangan sains, inspirasi untuk Reformasi Protestan",
        sumber_referensi: ["The Renaissance: A Short History", "Renaissance Art and Culture"],
        kategori: "Gerakan Seni dan Budaya"
      },
      {
        judul_sejarah: "Revolusi Amerika",
        deskripsi_sejarah: "Revolusi Amerika (1775-1783) adalah pemberontakan 13 koloni Amerika terhadap kekuasaan Britania Raya, dipicu oleh perpajakan tanpa representasi dan penindasan kolonial. Dipimpin oleh tokoh seperti George Washington, Thomas Jefferson, dan Benjamin Franklin, revolusi ini menghasilkan Deklarasi Kemerdekaan (1776).",
        periode: "1775-1783",
        kata_kunci: "revolusi, amerika, kemerdekaan, republik",
        wilayah: "Koloni Amerika Utara, Atlantik",
        tokoh_penting: ["George Washington", "Benjamin Franklin", "Thomas Jefferson", "John Adams", "Alexander Hamilton"],
        dampak: "Pembentukan USA, inspirasi revolusi Perancis, penyebaran ideologi demokratis, ekspansi Barat",
        penyebab: "Pajak yang tidak adil, kontrol perdagangan ketat, ketidakpuasan akan pemerintah kolonial",
        akibat: "Kemerdekaan USA, Konstitusi USA, Deklarasi Kemerdekaan, inspirasi gerakan kemerdekaan lainnya",
        sumber_referensi: ["The American Revolution: A History", "Founding Brothers by David McCullough"],
        kategori: "Revolusi"
      },
      {
        judul_sejarah: "Kekaisaran Ottoman",
        deskripsi_sejarah: "Kekaisaran Ottoman (1299-1922) adalah salah satu kerajaan terbesar, terkuat, dan terlama dalam sejarah dunia, berkuasa selama lebih dari 600 tahun. Didirikan oleh Osman I dan berkembang menjadi superkekuatan yang menguasai tiga benua (Eropa, Asia, Afrika). Ottoman terkenal dengan inovasi militer (penggunaan senjata api dan Janissaries), arsitektur megah (Masjid Biru, Taj Mahal).",
        periode: "1299-1922",
        kata_kunci: "ottoman, turki, kerajaan, islam",
        wilayah: "Turki, Balkans, Timur Tengah, Afrika Utara",
        tokoh_penting: ["Osman I", "Mehmed II", "Suleiman the Magnificent", "Ibrahim Pasha"],
        dampak: "Kontrol jalur perdagangan strategis, penyebaran budaya Islam, arsitektur Ottoman yang megah",
        penyebab: "Ekspansi militer, kelemahan Kekaisaran Bizantium, ambisi untuk kekuasaan",
        akibat: "Jatuh di Perang Dunia Pertama, pembentukan Turki modern, perpecahan Timur Tengah",
        sumber_referensi: ["The Ottoman Empire: 1700-1922", "Inside the Seraglio by Godfrey Goodwin"],
        kategori: "Kekaisaran"
      },
      {
        judul_sejarah: "Peradaban Yunani Kuno",
        deskripsi_sejarah: "Peradaban Yunani Kuno (800 SM - 146 SM) adalah peradaban awal Eropa yang menciptakan fondasi budaya, filosofi, dan sains Barat. Yunani kuno mengembangkan sistem demokrasi di Athena, filsafat dari Sokrates, Plato, dan Aristoteles, serta seni dan arsitektur klasik yang terkenal.",
        periode: "800 SM - 146 SM",
        kata_kunci: "yunani, kuno, filosofi, demokrasi",
        wilayah: "Yunani, Mediterania",
        tokoh_penting: ["Sokrates", "Plato", "Aristoteles", "Alexander the Great", "Perikles"],
        dampak: "Demokrasi Athena, filosofi Barat, seni dan arsitektur klasik, sains dan matematika",
        penyebab: "Geografi pulau yang mendorong independensi, perdagangan maritim, kontak dengan Timur Tengah",
        akibat: "Pengaruh abadi pada sains, filsafat, seni, penaklukan Alexander menyebarkan budaya Yunani",
        sumber_referensi: ["Ancient Greece: A Political, Social, and Cultural History", "The Greek Way by Edith Hamilton"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Peradaban Mesopotamia",
        deskripsi_sejarah: "Peradaban Mesopotamia (3500 SM - 539 SM) adalah salah satu peradaban tertua di dunia, berkembang di antara Sungai Tigris dan Eufrat (wilayah Irak modern). Mesopotamia menciptakan banyak inovasi penting: tulisan cuneiform (sistem penulisan pertama), roda, perahu berlayar, dan pemerintahan terorganisir.",
        periode: "3500 SM - 539 SM",
        kata_kunci: "mesopotamia, babylon, asur, cuneiform",
        wilayah: "Mesopotamia (Irak modern), Timur Tengah",
        tokoh_penting: ["Hammurabi", "Nebuchadnezzar II", "Sargon of Akkad"],
        dampak: "Sistem penulisan cuneiform pertama, Kode Hammurabi, matematika dan astronomi, organisasi pemerintahan",
        penyebab: "Posisi geografis antara dua sungai, pertanian yang berkembang, perdagangan",
        akibat: "Fondasi peradaban Timur Tengah, pengaruh pada Mesir dan Yunani, penaklukan Persia",
        sumber_referensi: ["The Sumerians: Their History, Culture, and Character", "Mesopotamia: The Invention of the City"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Zaman Es",
        deskripsi_sejarah: "Zaman Es (2.58 juta tahun lalu - 11.700 tahun lalu) adalah periode geologis ketika lapisan es tebal menutup sebagian besar planet Bumi, terutama di belahan bumi utara. Periode ini mencakup beberapa siklus pencairan dan pendinginan, mengubah iklim, laut, dan lanskap drastis.",
        periode: "2.58 juta - 11.700 tahun lalu",
        kata_kunci: "zaman, es, geologis, manusia",
        wilayah: "Global - belahan bumi utara terutama",
        tokoh_penting: ["Manusia Neanderthal", "Manusia Cro-Magnon", "Lucy (Australopithecus)"],
        dampak: "Evolusi manusia, migrasi global, pembentukan geografi planet, adaptasi manusia terhadap iklim ekstrem",
        penyebab: "Siklus Milankovitch, variasi orbit Bumi, aktivitas matahari",
        akibat: "Zaman Es berakhir, peningkatan suhu, pertanian dapat berkembang, peradaban dimulai",
        sumber_referensi: ["The Ice Age by John Imbrie", "When the World Was Young by Rainer Maria Rilke"],
        kategori: "Era Geologis"
      },
      {
        judul_sejarah: "Eksplorasi Eropa",
        deskripsi_sejarah: "Eksplorasi Eropa (1400-1700) adalah periode ketika pelayar dan penjelajah Eropa menjelajahi dunia, menemukan rute laut baru, dan memperluas pengetahuan geografis. Didorong oleh pencarian rute perdagangan ke Timur dan kerinduan emas, penjelajah seperti Kolumbus, Vasco da Gama, dan Magellan berlayar ke benua baru.",
        periode: "1400-1700",
        kata_kunci: "eksplorasi, eropa, penjelajahan, peta",
        wilayah: "Global - semua benua",
        tokoh_penting: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "James Cook", "Sir Francis Drake"],
        dampak: "Kolonialisasi global, perdagangan internasional, transfer budaya, penyebaran penyakit, ekonomi dunia",
        penyebab: "Pencarian rute perdagangan baru, ambisi kerajaan, kemajuan teknologi maritim",
        akibat: "Kekayaan Eropa, penderitaan koloni, perdagangan budak, transformasi ekonomi dunia",
        sumber_referensi: ["1492: Conquest, Catastrophe, and Conquest", "The Global Atlantic 1400-1900"],
        kategori: "Era Eksplorasi"
      },
      {
        judul_sejarah: "Peradaban Harappa",
        deskripsi_sejarah: "Peradaban Harappa (3300 SM - 1300 SM), juga dikenal sebagai Peradaban Lembah Indus, adalah salah satu peradaban tertua di Asia Selatan. Terletak di wilayah Pakis tan dan India modern, peradaban ini menciptakan kota-kota besar yang terencana dengan baik seperti Mohenjo-daro dan Harappa.",
        periode: "3300 SM - 1300 SM",
        kata_kunci: "harappa, indus, peradaban, urban",
        wilayah: "Lembah Indus (Pakistan dan India modern)",
        tokoh_penting: ["Penduduk Mohenjo-daro", "Penduduk Harappa"],
        dampak: "Sistem urban yang maju, sistem drainase canggih, perdagangan jarak jauh, pengaruh pada budaya India",
        penyebab: "Posisi geografis di lembah subur, pertanian yang berkembang, perdagangan",
        akibat: "Runtuh misterius sekitar 1300 SM, mungkin karena perubahan iklim atau invasi, pengaruh pada Veda India",
        sumber_referensi: ["The Indus Civilization", "Harappa: One of the World's Great Cities"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Dinasti Zhou",
        deskripsi_sejarah: "Dinasti Zhou (1046 SM - 256 SM) adalah dinasti Tiongkok tertua dan terlama, mendominasi sejarah Tiongkok Kuno selama 800 tahun. Dinasti Zhou dimulai dengan penaklukan Dinasti Shang dan membawa konsep Mandate of Heaven untuk menggambarkan legitimasi kekuasaan.",
        periode: "1046 SM - 256 SM",
        kata_kunci: "zhou, dinasti, tiongkok, filsafat",
        wilayah: "Tiongkok",
        tokoh_penting: ["King Wu of Zhou", "Kongzi (Confucius)", "Laozi", "King Wen of Zhou"],
        dampak: "Filosofi Konfusianisme dan Taoisme, sistem feudal, perkembangan pertanian dan teknologi",
        penyebab: "Penaklukan Dinasti Shang, ambisi untuk kekuasaan, stabilitas",
        akibat: "Fragmentasi ke periode Negara Berperang, warisan filosofi mendominasi Tiongkok",
        sumber_referensi: ["The Zhou Dynasty: Ancient China's Classical Age", "The Way of the Sage by Confucius"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Abad Pertengahan",
        deskripsi_sejarah: "Abad Pertengahan (500-1500) adalah periode setelah jatuhnya Kekaisaran Romawi Barat hingga awal era modern, mencakup 1000 tahun sejarah Eropa. Periode ini ditandai dengan sistem feodal, fragmentasi kekuatan, dan dominasi Gereja Katolik dalam kehidupan intelektual dan spiritual.",
        periode: "500-1500",
        kata_kunci: "abad, pertengahan, feodal, gereja",
        wilayah: "Eropa",
        tokoh_penting: ["Charlemagne", "Pope Gregory the Great", "Richard the Lionheart", "Joan of Arc"],
        dampak: "Sistem feodal, dominasi Gereja, perkembangan universitas, perang salib, seni gothic",
        penyebab: "Jatuhnya Romawi Barat, invasi barbar, kebutuhan struktur sosial baru",
        akibat: "Fondasi Eropa modern, perdagangan berkembang, teknologi meningkat, akhir feodalism",
        sumber_referensi: ["The Medieval World", "The Normans: From Raiding to Kings by James Muldoon"],
        kategori: "Era Historis"
      },
      {
        judul_sejarah: "Kesultanan Umayyah",
        deskripsi_sejarah: "Kesultanan Umayyah (661-750 M) adalah dinasti Islam pertama yang menguasai wilayah sangat luas dari Spanyol dan Afrika Utara hingga India. Didirikan oleh Muawiya I setelah peperangan suksesi, Umayyah menciptakan struktur pemerintahan terorganisir dan militer kuat.",
        periode: "661-750 M",
        kata_kunci: "umayyah, islam, dinasti, arab",
        wilayah: "Timur Tengah, Afrika Utara, Spanyol, Asia Selatan",
        tokoh_penting: ["Muawiya I", "Abd al-Malik", "Umar II"],
        dampak: "Penyebaran Islam, arsitektur Islam awal, administrasi pemerintahan, budaya Arab",
        penyebab: "Ekspansi Islam, kepemimpinan Muawiya, stabilisasi khilafah",
        akibat: "Jatuh ke Dinasti Abbasiyah, pengaruh pada peradaban Islam, warisan administratif",
        sumber_referensi: ["The Umayyad Period", "The Dawn of the Medieval World by Peter Brown"],
        kategori: "Dinasti Islam"
      },
      {
        judul_sejarah: "Perang Sipil Amerika",
        deskripsi_sejarah: "Perang Sipil Amerika (1861-1865) adalah konflik internal paling besar di Amerika Serikat antara Uni (negara-negara bagian Utara) dan Konfederasi (11 negara bagian Selatan yang memisahkan diri). Perang ini dipicu oleh perbedaan ideologi tentang perbudakan, hak negara bagian, dan industrialisasi.",
        periode: "1861-1865",
        kata_kunci: "sipil, amerika, perbudakan, union",
        wilayah: "Amerika Serikat (Utara dan Selatan)",
        tokoh_penting: ["Abraham Lincoln", "Robert E. Lee", "Ulysses S. Grant", "Jefferson Davis"],
        dampak: "Pengakhiran perbudakan, perkuat federalisme, perubahan industri ke arah Utara, Rekonstruksi",
        penyebab: "Perbudakan, hak negara bagian, ekonomi Utara vs Selatan, pemilihan Lincoln",
        akibat: "600,000 korban jiwa, Amandemen ke-13/14/15, transformasi sosial Amerika, hegemoni Utara",
        sumber_referensi: ["The Civil War: A Narrative", "Team of Rivals by Doris Kearns Goodwin"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Era Pencerahan",
        deskripsi_sejarah: "Era Pencerahan (1650-1780) adalah gerakan intelektual dan filosofis yang menekankan akal, sains, dan pertanyaan skeptis terhadap otoritas tradisional dan agama. Tokoh-tokoh seperti Descartes, Newton, Locke, Voltaire, Rousseau, dan Kant mengembangkan ide-ide tentang hak-hak manusia, pemerintahan konstitusional, dan pemisahan kekuasaan.",
        periode: "1650-1780",
        kata_kunci: "pencerahan, sains, rasionalisme, filosofi",
        wilayah: "Eropa (terutama Perancis, Inggris, Jerman)",
        tokoh_penting: ["John Locke", "Voltaire", "Rousseau", "Isaac Newton", "Francis Bacon", "Descartes"],
        dampak: "Fondasi demokrasi, hak asasi manusia, metode ilmiah, revolusi Perancis dan Amerika",
        penyebab: "Reaksi terhadap dogmatisme agama, kemajuan ilmu pengetahuan, pertumbuhan kelas menengah",
        akibat: "Ide-ide liberal, reformasi pendidikan, mengakhiri Feudalisme intelektual",
        sumber_referensi: ["The Enlightenment: A Secular History", "The Ideas of the Enlightenment"],
        kategori: "Gerakan Intelektual"
      },
      {
        judul_sejarah: "Kekaisaran Mongol",
        deskripsi_sejarah: "Kekaisaran Mongol (1206-1368) adalah salah satu kekaisaran terbesar dalam sejarah, mencakup area dari Cina hingga Eropa Timur. Didirikan oleh Genghis Khan (Temüjin), Mongol menciptakan kekaisaran yang menaklukkan lebih dari 2 juta kilometer persegi dengan tentara berkuda terlatih dan taktik militer canggih.",
        periode: "1206-1368",
        kata_kunci: "mongol, genghis, kekaisaran, jalur sutra",
        wilayah: "Asia, Eropa, dari Atlantik hingga Pasifik",
        tokoh_penting: ["Genghis Khan (Temujin)", "Kublai Khan", "Möngke Khan", "Chagatai"],
        dampak: "Jalur Sutra diperkuat, pertukaran budaya Timur-Barat, pembentukan beberapa negara modern",
        penyebab: "Unifikasi suku Mongolia, strategi militer inovatif, keinginan ekspansi",
        akibat: "Dinasti Yuan di Cina, kekaisaran terbesar, tetapi fragmentasi setelah Genghis Khan",
        sumber_referensi: ["The Mongol Empire", "Genghis Khan: His Conquests, His Empire"],
        kategori: "Kekaisaran"
      },
      {
        judul_sejarah: "Zaman Kerajaan Besar",
        deskripsi_sejarah: "Zaman Kerajaan Besar (1500-1900) adalah era ekspansi imperial ketika negara-negara Eropa, terutama Spanyol, Portugal, Inggris, Belanda, dan Perancis, memperluas wilayah kolonial ke seluruh dunia. Periode ini mencakup penaklukan Amerika, Afrika, dan Asia, dengan tujuan mencari sumber daya, pasar, dan kekuasaan.",
        periode: "1500-1900",
        kata_kunci: "kerajaan, besar, kolonial, ekspansi",
        wilayah: "Global - Amerika, Afrika, Asia, Australia",
        tokoh_penting: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "James Cook", "Sir Francis Drake"],
        dampak: "Kolonialisasi global, perdagangan internasional, transfer budaya, ekonomi dunia modern",
        penyebab: "Pencarian rute perdagangan, ambisi kekuasaan kerajaan, teknologi maritim yang berkembang",
        akibat: "Kekayaan Eropa, penderitaan koloni, perdagangan budak, ketidakseimbangan ekonomi global",
        sumber_referensi: ["1492: Conquest, Catastrophe, and Conquest", "The Global Atlantic 1400-1900"],
        kategori: "Era Eksplorasi"
      },
      {
        judul_sejarah: "Revolusi Rusia",
        deskripsi_sejarah: "Revolusi Rusia (1917) adalah pergantian rezim radikal di Rusia yang menggulingkan Tsar Nikolaus II dan Pemerintah Sementara, menghasilkan Uni Soviet. Dipimpin oleh Vladimir Lenin dan Partai Bolshevik, revolusi ini mewujudkan ideologi komunisme dengan penghapusan kepemilikan pribadi dan distribusi kekayaan komunal.",
        periode: "1917",
        kata_kunci: "revolusi, rusia, soviet, lenin, komunis",
        wilayah: "Rusia, Uni Soviet",
        tokoh_penting: ["Vladimir Lenin", "Leon Trotsky", "Joseph Stalin", "Nicholas II", "Alexander Kerensky"],
        dampak: "Pembentukan Uni Soviet, ideologi komunis menyebar, Perang Dingin, transformasi global",
        penyebab: "Perang Dunia Pertama, kelaparan, ketidakpuasan sosial, ide-ide Marxis",
        akibat: "Tsar dieksekusi, negara komunis pertama, Perang Sipil, era Stalin dengan penindasan",
        sumber_referensi: ["The Bolshevik Revolution", "A People's Tragedy by Orlando Figes"],
        kategori: "Revolusi"
      },
      {
        judul_sejarah: "Renaisans Islam",
        deskripsi_sejarah: "Renaisans Islam (750-1400) adalah periode emas ketika dunia Islam mengalami kemajuan luar biasa dalam sains, matematika, filsafat, dan budaya. Dimulai dengan Dinasti Abbasiyah, periode ini menghasilkan tokoh-tokoh besar seperti Al-Khwarizmi (aljabar), Al-Razi (kimia), Ibn Sina (kedokteran), dan Al-Ghazali (filosofi).",
        periode: "750-1400",
        kata_kunci: "renaisans, islam, sains, budaya",
        wilayah: "Dunia Islam (Timur Tengah, Afrika Utara, Asia Selatan, Andalusia)",
        tokoh_penting: ["Al-Khwarizmi", "Al-Razi", "Ibn Sina", "Al-Ghazali", "Al-Farabi"],
        dampak: "Universitas dan perpustakaan besar, kemajuan sains, matematika, astronomi, kedokteran",
        penyebab: "Dinasti Abbasiyah yang stabil, perlindungan terhadap cendekiawan, terjemahan karya Yunani",
        akibat: "Ilmu pengetahuan menyebar ke Eropa, kontribusi pada Renaissance Eropa",
        sumber_referensi: ["The House of Wisdom", "Islamic Golden Age: The Foundations of Science"],
        kategori: "Era Emas Islam"
      },
      {
        judul_sejarah: "Peradaban Aztek",
        deskripsi_sejarah: "Peradaban Aztek (1345-1521) adalah peradaban Amerika Pra-Columbus yang maju dengan ibu kota besar Tenochtitlan (Mexico City modern). Aztek menciptakan kerajaan yang terorganisir dengan sistem pemerintahan hierarki, tentara kuat, dan sistem perpajakan efisien.",
        periode: "1345-1521",
        kata_kunci: "aztek, mexico, peradaban, tenochtitlan",
        wilayah: "Mexico, Amerika Tengah",
        tokoh_penting: ["Montezuma I", "Montezuma II", "Hernán Cortés"],
        dampak: "Arsitektur megah, sistem pertanian canggih (chinampas), astronomi yang maju",
        penyebab: "Migrasi dari Aztlán, konsolidasi kekuatan, ekspansi militer",
        akibat: "Ditaklukkan Spanyol 1521, akhir peradaban pra-Kolumbia, kolonisasi Spanyol Amerika",
        sumber_referensi: ["The Aztecs: The Last Great Civilization", "The World of the Aztecs"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Dinasti Han",
        deskripsi_sejarah: "Dinasti Han (206 SM - 220 M) adalah dinasti Tiongkok yang mengalami kemakmuran dan keemasan besar, mendominasi Tiongkok selama 426 tahun. Dinasti Han didirikan oleh Liu Bang setelah Dinasti Qin, membawa stabilitas, ekspansi wilayah, dan kemajuan budaya.",
        periode: "206 SM - 220 M",
        kata_kunci: "han, dinasti, tiongkok, jalur sutra",
        wilayah: "Tiongkok",
        tokoh_penting: ["Liu Bang (Emperor Gaozu)", "Emperor Kangxi", "Zheng He"],
        dampak: "Jalur Sutra dikembangkan, seni dan literatur berkembang, teknologi pembuatan kertas",
        penyebab: "Perlawanan terhadap Dinasti Qin yang keras, perlucutan kekuatan Qin",
        akibat: "Periode emas budaya Cina, identitas Cina diperkuat, orang Cina disebut \"Han Chinese\"",
        sumber_referensi: ["The Han Dynasty", "The Silk Road: A New History"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Peradaban Inca",
        deskripsi_sejarah: "Peradaban Inca (1438-1532) adalah kerajaan Amerika Pra-Columbus terbesar di Amerika Selatan, mencakup wilayah luas dari modern Ekuador hingga Chile. Inca menciptakan kerajaan terorganisir dengan sistem pemerintahan terpusat, tentara profesional, dan sistem administrasi canggih (quipu - sistem pencatatan dengan tali berwarna).",
        periode: "1438-1532",
        kata_kunci: "inca, peru, peradaban, machu picchu",
        wilayah: "Amerika Selatan (Peru, Ecuador, Bolivia, Chile, Argentina)",
        tokoh_penting: ["Pachacuti", "Huayna Capac", "Francisco Pizarro"],
        dampak: "Arsitektur megah (Machu Picchu), sistem jalan 40.000 km, irigasi canggih",
        penyebab: "Unifikasi suku-suku Andean, ambisi ekspansi, iklim Andes yang stabil",
        akibat: "Ditaklukkan Spanyol 1532, akhir peradaban pra-Kolumbia besar, kolonisasi Spanyol",
        sumber_referensi: ["The Incas: People of the Sun", "Machu Picchu: The Search for the Lost City"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Reformasi Protestan",
        deskripsi_sejarah: "Reformasi Protestan (1517-1648) adalah gerakan keagamaan dan sosial yang dimulai dengan Martin Luther menentang praktik Gereja Katolik Romawi, khususnya penjualan indulgensi. Luther menerbitkan 95 Tesis yang mengkritik otoritas Paus dan menekankan kembali ke Kitab Suci.",
        periode: "1517-1648",
        kata_kunci: "reformasi, protestan, gereja, martin luther",
        wilayah: "Eropa (terutama Jerman, Skandinavia, Inggris)",
        tokoh_penting: ["Martin Luther", "John Calvin", "Ulrich Zwingli", "Henry VIII", "Thomas Cranmer"],
        dampak: "Perpecahan Kristen, denominasi Protestan, pemisahan gereja dan negara, kebebasan beragama",
        penyebab: "Ketidakpuasan terhadap praktik Gereja, korupsi Vatikan, penjualan indulgensi",
        akibat: "Perang Salib 30 Tahun, transformasi Eropa, perkembangan kapitalisme modern",
        sumber_referensi: ["The Reformation: A History", "The Protestant Ethic and the Spirit of Capitalism"],
        kategori: "Gerakan Religius"
      },
      {
        judul_sejarah: "Revolusi Teknologi Digital",
        deskripsi_sejarah: "Revolusi Teknologi Digital (1960-sekarang) adalah periode transformasi pesat dalam teknologi komputer, internet, dan komunikasi. Dimulai dengan komputer mainframe, berkembang menjadi PC, internet, dan perangkat mobile yang mengubah cara manusia berkomunikasi, bekerja, berbisnis, dan belajar.",
        periode: "1960-sekarang",
        kata_kunci: "digital, teknologi, internet, komputer, ai",
        wilayah: "Global (dimulai dari Amerika Serikat)",
        tokoh_penting: ["Alan Turing", "Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Mark Zuckerberg"],
        dampak: "Globalisasi informasi, ekonomi digital, transformasi industri, perubahan cara hidup manusia",
        penyebab: "Inovasi komputer, perkembangan mikroprosesor, kebutuhan komunikasi global",
        akibat: "Internet tersebar luas, media sosial dominan, e-commerce, AI, transformasi pasar kerja",
        sumber_referensi: ["The Information: A History", "Coding: A Brief History"],
        kategori: "Revolusi Teknologi"
      },
      {
        judul_sejarah: "Peradaban Maya",
        deskripsi_sejarah: "Peradaban Maya (2000 SM - 1500 M) adalah peradaban maju Amerika Pra-Columbus dengan kota-kota besar, sistem penulisan hieroglif, dan perhitungan matematika canggih. Pusat budaya Maya mencakup Tikal, Copán, dan Palenque dengan arsitektur piramida yang menakjubkan.",
        periode: "2000 SM - 1500 M",
        kata_kunci: "maya, mesoamerika, piramida, kalender",
        wilayah: "Amerika Tengah (Mexico, Guatemala, Belize, Honduras)",
        tokoh_penting: ["Jasaw Chan K'awiil", "Pakal", "Ah Cacao"],
        dampak: "Sistem penulisan hieroglif, matematika dengan konsep nol, kalender astronomi presisi tinggi",
        penyebab: "Pertanian maju, perdagangan, kemajuan astronomi",
        akibat: "Runtuhnya kota-kota Maya klasik, era postklasik, kolonialisasi Spanyol",
        sumber_referensi: ["The Maya: A Very Short Introduction", "The Code of Kings by Linda Schele"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Imperium Persia",
        deskripsi_sejarah: "Imperium Persia (550 SM - 330 SM) adalah kerajaan besar yang didirikan oleh Cyrus the Great, mencakup wilayah dari Mesir hingga India. Persia terkenal dengan sistem administrasi terorganisir, toleransi religius, dan jalan raya besar (Royal Road).",
        periode: "550 SM - 330 SM",
        kata_kunci: "persia, cyrus, kerajaan, achaemenid",
        wilayah: "Timur Tengah, Mesir, Asia Selatan, Asia Kecil",
        tokoh_penting: ["Cyrus the Great", "Darius I", "Xerxes I", "Alexander the Great"],
        dampak: "Sistem postal terorganisir, toleransi religius, arsitektur Persepolis, filosofi Zoroastrianisme",
        penyebab: "Unifikasi suku-suku Persian, ekspansi militer, ambisi hegemoni",
        akibat: "Ditaklukkan Alexander Agung 330 SM, warisan administrasi berlanjut",
        sumber_referensi: ["The Persian Empire", "From Cyrus to Alexander by Pierre Briant"],
        kategori: "Kekaisaran"
      },
      {
        judul_sejarah: "Kekaisaran Mughal",
        deskripsi_sejarah: "Kekaisaran Mughal (1526-1857) adalah kekaisaran Islam besar di Asia Selatan yang menguasai India, Pakistan, dan Bangladesh. Dibangun oleh Babur, Mughal menciptakan seni, arsitektur, dan budaya yang kaya dengan monumen ikonik seperti Taj Mahal.",
        periode: "1526-1857",
        kata_kunci: "mughal, india, taj mahal, islam",
        wilayah: "India, Pakistan, Bangladesh, Asia Selatan",
        tokoh_penting: ["Babur", "Akbar the Great", "Shah Jahan", "Aurangzeb"],
        dampak: "Taj Mahal dan arsitektur Mughal, seni miniatur, sastra Urdu, administrasi sentralisasi",
        penyebab: "Invasi dari Turki/Afganistan, ambisi ekspansi, stabilitas kekuasaan",
        akibat: "Jatuh ke Inggris, warisan budaya bertahan, India Britania",
        sumber_referensi: ["The Mughal Empire", "The Taj Mahal: A Love Story"],
        kategori: "Kekaisaran"
      },
      {
        judul_sejarah: "Kerajaan Khmer (Angkor)",
        deskripsi_sejarah: "Kerajaan Khmer (802-1431) adalah kerajaan besar Asia Tenggara dengan ibu kota Angkor, terkenal dengan Angkor Wat - kuil terbesar di dunia. Khmer mencapai puncak kekuasaan di bawah Suryavarman II dengan sistem irigasi canggih dan monumen arsitektur megah.",
        periode: "802-1431",
        kata_kunci: "khmer, angkor, cambodia, candi",
        wilayah: "Kamboja, Asia Tenggara",
        tokoh_penting: ["Jayavarman II", "Suryavarman II", "Jayavarman VII"],
        dampak: "Angkor Wat - kuil terbesar dunia, sistem irigasi kompleks, seni dan arsitektur Khmer",
        penyebab: "Konsolidasi kekuasaan, kemajuan irigasi, perdagangan Timur-Barat",
        akibat: "Runtuh akibat tekanan Thai dan perubahan iklim, Angkor ditinggalkan",
        sumber_referensi: ["Angkor and the Khmer", "The Civilizations of the Khmer"],
        kategori: "Kerajaan"
      },
      {
        judul_sejarah: "Kerajaan Srivijaya dan Majapahit",
        deskripsi_sejarah: "Kerajaan Srivijaya (650-1377) dan Majapahit (1293-1527) adalah kerajaan maritim besar Nusantara yang mendominasi perdagangan Asia Tenggara. Srivijaya terkenal dengan kekuatan laut dan pusat pembelajaran Buddha, sedangkan Majapahit menciptakan wilayah nusantara terpadu.",
        periode: "650-1527",
        kata_kunci: "srivijaya, majapahit, nusantara, maritim",
        wilayah: "Kepulauan Nusantara (Indonesia modern)",
        tokoh_penting: ["Balaputra", "Sailendra", "Gajah Mada", "Hayam Wuruk"],
        dampak: "Dominasi perdagangan maritim, penyebaran Buddha, fondasi identitas nusantara, budaya Hindu-Budha",
        penyebab: "Lokasi strategis jalur perdagangan, kemajuan pelayaran, kestabilan pemerintahan",
        akibat: "Jatuh ke Kesultanan Demak, warisan budaya Hindu-Budha bertahan, fondasi Indonesia modern",
        sumber_referensi: ["Srivijaya and the Silk Road", "Majapahit: The End of an Eastern Empire"],
        kategori: "Kerajaan Maritim"
      },
      {
        judul_sejarah: "Revolusi Meiji (Jepang)",
        deskripsi_sejarah: "Revolusi Meiji (1868-1912) adalah transformasi fundamental Jepang dari negara feodal tertutup menjadi kekuatan modern industri. Dimulai dengan Restorasi Meiji yang menghilangkan sistem shogunat, Jepang melakukan industrialisasi, modernisasi militer, dan reformasi sosial cepat.",
        periode: "1868-1912",
        kata_kunci: "meiji, jepang, modernisasi, revolusi",
        wilayah: "Jepang",
        tokoh_penting: ["Emperor Meiji", "Iwakura Tomomi", "Ito Hirobumi", "Mori Arinori"],
        dampak: "Industrialisasi Jepang, kekuatan militer modern, sistem pendidikan modern, imperialisme Asia",
        penyebab: "Ketidakpuasan dengan shogunat feodal, tekanan Barat (Commodore Perry), ambisi modernisasi",
        akibat: "Jepang menjadi kekuatan besar, ekspansi imperialis, Perang Rusia-Jepang",
        sumber_referensi: ["The Meiji Restoration", "Japan: The New Superpower by Clyde Prestowitz"],
        kategori: "Revolusi Modernisasi"
      },
      {
        judul_sejarah: "Perang Salib",
        deskripsi_sejarah: "Perang Salib (1096-1291) adalah serangkaian perang religius antara Kristen Eropa dan Dunia Islam atas kontrol tanah suci Palestina dan Yerusalem. Delapan perang utama melibatkan ribuan tentara, perjalanan jauh, dan konflik budaya yang intens.",
        periode: "1096-1291",
        kata_kunci: "salib, perang, religius, yerusalem",
        wilayah: "Timur Tengah (Levant), Palestina, Yerusalem",
        tokoh_penting: ["Saladin", "Richard the Lionheart", "Urban II", "Godfrey of Bouillon"],
        dampak: "Pertukaran budaya Timur-Barat, peningkatan perdagangan, ketegangan religius berkelanjutan",
        penyebab: "Seruan Paus Urban II, kekhawatiran terhadap ekspansi Islam, motivasi religius dan ekonomis",
        akibat: "Kemenangan ultimate Saladin, Yerusalem tetap Muslim, dampak jangka panjang pada hubungan Islam-Kristen",
        sumber_referensi: ["The Crusades: War for the Holy Land", "A History of the Crusades"],
        kategori: "Perang Religius"
      },
      {
        judul_sejarah: "Periode Edo (Jepang)",
        deskripsi_sejarah: "Periode Edo (1603-1868) adalah era perdamaian dan stabilitas Jepang di bawah pemerintahan Tokugawa Shogunate. Jepang menerapkan kebijakan isolasi (sakoku) yang menghentikan kontak dengan dunia luar kecuali Belanda dan China, menciptakan budaya yang unik dan berkembang.",
        periode: "1603-1868",
        kata_kunci: "edo, jepang, shogunate, tokugawa, isolasi",
        wilayah: "Jepang",
        tokoh_penting: ["Tokugawa Ieyasu", "Tokugawa Iemitsu"],
        dampak: "Stabilitas sosial 250 tahun, perkembangan budaya seni dan sastra unik, sistem feodal yang terorganisir",
        penyebab: "Perang Sengoku yang berakhir, ambisi Tokugawa untuk stabilitas, kebijakan isolasi",
        akibat: "Budaya Edo yang kaya (ukiyo-e, kabuki), berakhir dengan Restorasi Meiji",
        sumber_referensi: ["The Edo Period", "Floating World: Japanese Popular Prints"],
        kategori: "Era Historis"
      },
      {
        judul_sejarah: "Dinasti Qing",
        deskripsi_sejarah: "Dinasti Qing (1644-1912) adalah dinasti terakhir Tiongkok, diperintah oleh etnis Manchu yang menaklukkan Cina. Qing mencapai kemakmuran besar di abad ke-18 tetapi mengalami kemunduran dan ketidakstabilan di abad ke-19 menghadapi imperialisme Barat.",
        periode: "1644-1912",
        kata_kunci: "qing, dinasti, manchu, tiongkok, imperialisme",
        wilayah: "Tiongkok, Mongolia, Tibet, Xinjiang",
        tokoh_penting: ["Kangxi", "Yongzheng", "Qianlong", "Empress Dowager Cixi"],
        dampak: "Ekspansi teritorial Cina, seni dan porselain Qing berkembang, tetapi kemunduran menghadapi Barat",
        penyebab: "Penaklukan Manchu, ambisi mempersatukan Cina, stabilisasi pemerintahan",
        akibat: "Perang Opium, Jepang modern, kemunduran, Revolusi Cina 1912, jatuhnya dinasti",
        sumber_referensi: ["The Qing Dynasty", "1421: The Year China Discovered the World"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Ekspansi Arab Awal",
        deskripsi_sejarah: "Ekspansi Arab Awal (632-750 M) adalah periode ketika Arab Muslim memperluas wilayahnya dengan cepat dari Semenanjung Arabia ke Timur Tengah, Afrika Utara, dan Spanyol. Dalam satu abad, Islam menyebar ke wilayah yang sangat luas melalui penaklukan dan dakwah.",
        periode: "632-750 M",
        kata_kunci: "arab, islam, ekspansi, penaklukan",
        wilayah: "Timur Tengah, Afrika Utara, Spanyol, Asia",
        tokoh_penting: ["Prophet Muhammad", "Abu Bakr", "Umar", "Ali", "Khalid ibn al-Walid"],
        dampak: "Penyebaran Islam yang cepat, pembentukan Khilafah, budaya Arab mendominasi",
        penyebab: "Ajaran Islam yang kuat, kepemimpinan militer terampil, fragmentasi Kekaisaran Sasanid",
        akibat: "Penyebaran Renaisans Islam, pembentukan Kesultanan Umayyah, transformasi Timur Tengah",
        sumber_referensi: ["A History of the Arabs", "The Early Islamic Conquests"],
        kategori: "Ekspansi Keagamaan"
      },
      {
        judul_sejarah: "Peradaban Minoan",
        deskripsi_sejarah: "Peradaban Minoan (3000 SM - 1100 SM) adalah peradaban Kreta kuno yang berkembang dengan arsitektur megah, seni berkualitas tinggi, dan sistem perdagangan maritim maju. Minoan adalah peradaban Eropa tertua yang signifikan dengan ibu kota Knossos.",
        periode: "3000 SM - 1100 SM",
        kata_kunci: "minoan, kreta, peradaban, kuno",
        wilayah: "Kreta, Laut Aegean",
        tokoh_penting: ["Minos", "Daedalus"],
        dampak: "Arsitektur istana yang kompleks, seni dan keramik halus, perdagangan maritim",
        penyebab: "Lokasi strategis Kreta, perdagangan, iklim yang subur",
        akibat: "Dihancurkan oleh letusan vulkanik atau invasi Mycenaean, pengaruh pada Yunani kuno",
        sumber_referensi: ["The Minoans", "Minoan Crete by Donald Preziosi"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Era Pemerintahan Firaun Baru (Mesir)",
        deskripsi_sejarah: "Era Pemerintahan Firaun Baru (1550 SM - 1070 SM) adalah periode kekuasaan maksimal Mesir Kuno dengan ekspansi wilayah, arsitektur megah, dan stabilitas pemerintahan. Dipimpin oleh firaun kuat seperti Thutmose III, Amenhotep III, dan Ramesses II.",
        periode: "1550 SM - 1070 SM",
        kata_kunci: "firaun, mesir, baru, empire",
        wilayah: "Mesir, Nubia, Levant",
        tokoh_penting: ["Thutmose III", "Amenhotep III", "Ramesses II", "Ramesses III"],
        dampak: "Ekspansi wilayah Mesir, pembangunan monumen besar (Abu Simbel, Karnak), seni dan sastra maju",
        penyebab: "Stabilitas pemerintahan, kepemimpinan militer kuat, kontrol perdagangan",
        akibat: "Kemundur di akhir periode, invasi Laut Utara, era perunggu berakhir",
        sumber_referensi: ["The New Kingdom of Ancient Egypt", "Ramesses II and His Time"],
        kategori: "Era Dinastik"
      },
      {
        judul_sejarah: "Perang Napoleon",
        deskripsi_sejarah: "Perang Napoleon (1803-1815) adalah serangkaian konflik besar antara Perancis di bawah Napoleon Bonaparte dan koalisi negara Eropa lainnya. Napoleon melakukan ekspansi wilayah Perancis ke seluruh Eropa Kontinental sebelum akhirnya dikalahkan.",
        periode: "1803-1815",
        kata_kunci: "napoleon, perang, perancis, koalisi",
        wilayah: "Eropa (Perancis, Italia, Austria, Rusia, Inggris)",
        tokoh_penting: ["Napoleon Bonaparte", "Admiral Nelson", "Duke of Wellington", "Tsar Alexander I"],
        dampak: "Redefinisi peta Eropa, kode hukum Napoleon, penguatan nasionalisme, jatuh Kekaisaran Perancis",
        penyebab: "Ambisi Napoleon, Revolusi Perancis yang meluas, ketidakseimbangan kekuatan Eropa",
        akibat: "Kekalahan di Waterloo, pengasingan, restorasi monarki Bourbon, Kongres Wien",
        sumber_referensi: ["A History of the Napoleonic Wars", "Napoleon: A Life by Andrew Roberts"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Kekaisaran Austria-Hungaria",
        deskripsi_sejarah: "Kekaisaran Austria-Hungaria (1867-1918) adalah superkekuatan Eropa multi-etnis yang menguasai wilayah luas di Eropa Tengah. Terbentuk melalui Kompromi Austria-Hungaria, kekaisaran ini menghadapi ketegangan etnis internal dan ancaman eksternal yang mengakibatkan kehancurannya di Perang Dunia I.",
        periode: "1867-1918",
        kata_kunci: "austria, hungaria, kekaisaran, multi-etnis",
        wilayah: "Eropa Tengah dan Timur",
        tokoh_penting: ["Franz Joseph I", "Archduke Franz Ferdinand", "Count Aehrenthal"],
        dampak: "Kekuatan Eropa multi-etnis, budaya Wina yang kaya, musik dan seni berkembang",
        penyebab: "Kompromi antara Austria dan Hungaria, keseimbangan kekuatan Eropa",
        akibat: "Pembunuhan Franz Ferdinand memicu Perang Dunia I, kekalahan, pemecahan negara",
        sumber_referensi: ["The Habsburg Monarchy", "Austria-Hungary and the Origins of WWI"],
        kategori: "Kekaisaran"
      },
      {
        judul_sejarah: "Revolusi Cina 1912",
        deskripsi_sejarah: "Revolusi Cina 1912 adalah pemberontakan yang menggulingkan Dinasti Qing dan mendirikan Republik Cina. Dipimpin oleh Sun Yat-sen, revolusi ini berhasil menghilangkan monarki feodal dan menginspirasi reformasi sosial di Cina.",
        periode: "1912",
        kata_kunci: "revolusi, cina, republik, sun yat-sen",
        wilayah: "Cina",
        tokoh_penting: ["Sun Yat-sen", "Yuan Shikai", "Huang Xing", "Empress Dowager Cixi"],
        dampak: "Jatuh dinasti feodal, pembentukan Republik Cina, modernisasi Cina",
        penyebab: "Kemunduran Dinasti Qing, ketidakpuasan sosial, pengaruh Barat, kebutuhan reformasi",
        akibat: "Periode warlord, Perang Sipil Cina, akhirnya Komunis mengambil alih di 1949",
        sumber_referensi: ["The Chinese Revolution", "Sun Yat-sen and the Chinese Republic"],
        kategori: "Revolusi"
      },
      {
        judul_sejarah: "Renaisans Utara",
        deskripsi_sejarah: "Renaisans Utara (1400-1600) adalah periode perkembangan seni, sastra, dan pemikiran humanis di Eropa Utara (Belanda, Flanders, Jerman, Inggris). Meskipun terinspirasi oleh Renaisans Italia, Utara mengembangkan gaya seni unik dengan fokus pada detail realistis dan tema religius.",
        periode: "1400-1600",
        kata_kunci: "renaisans, utara, seni, humanisme",
        wilayah: "Eropa Utara (Flanders, Belanda, Jerman, Inggris)",
        tokoh_penting: ["Jan van Eyck", "Albrecht Dürer", "Pieter Bruegel", "Desiderius Erasmus"],
        dampak: "Perkembangan seni realistis, literatur humanis, cetakan dan engraving maju",
        penyebab: "Pengaruh Renaisans Italia, perdagangan makmur, kelas merchant yang kaya",
        akibat: "Kontribusi pada Reformasi Protestan, inspirasi seni Eropa selanjutnya",
        sumber_referensi: ["The Northern Renaissance", "Jan van Eyck and the Founders of Flemish Painting"],
        kategori: "Gerakan Seni dan Budaya"
      },
      {
        judul_sejarah: "Dinasti Song",
        deskripsi_sejarah: "Dinasti Song (960-1279) adalah dinasti Tiongkok yang mencapai puncak seni, sastra, dan ilmu pengetahuan selama Abad Pertengahan. Song terkenal dengan keramik halus, lukisan landscape indah, dan inovasi teknologi seperti kompas dan bubuk mesiu.",
        periode: "960-1279",
        kata_kunci: "song, dinasti, tiongkok, seni",
        wilayah: "Tiongkok",
        tokoh_penting: ["Emperor Taizu", "Emperor Huizong", "Su Shi", "Wang Xifeng"],
        dampak: "Seni dan sastra Song berkembang, teknologi dan inovasi maju, perdagangan internasional",
        penyebab: "Stabilitas pemerintahan, pemerintah yang mendukung seni, perdagangan maritim",
        akibat: "Ditaklukkan Mongol 1279, warisan seni dan budaya Song sangat berpengaruh",
        sumber_referensi: ["The Song Dynasty", "Landscape Painting in Chinese Culture"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Kekaisaran Mali",
        deskripsi_sejarah: "Kekaisaran Mali (1226-1600) adalah kekaisaran besar Afrika Barat yang terkenal dengan kekayaan emas dan pusat pembelajaran Islam. Mali mencapai puncak kekuasaan di bawah Mansa Musa yang melakukan perjalanan haji spektakuler ke Mekkah.",
        periode: "1226-1600",
        kata_kunci: "mali, kekaisaran, emas, mansa musa",
        wilayah: "Afrika Barat",
        tokoh_penting: ["Sundiata Keita", "Mansa Musa", "Suleiman"],
        dampak: "Perdagangan trans-Sahara, pusat pembelajaran Islam, arsitektur dan budaya Mali berkembang",
        penyebab: "Kontrol jalur perdagangan emas, ekspansi militer, kepemimpinan kuat",
        akibat: "Kemunduran akibat invasi Songhai, transformasi budaya Afrika Barat",
        sumber_referensi: ["Empire of Mali", "Mansa Musa: The Golden King"],
        kategori: "Kekaisaran"
      },
      {
        judul_sejarah: "Dinasti Safavid (Persia)",
        deskripsi_sejarah: "Dinasti Safavid (1501-1736) adalah kekaisaran Islam besar di Persia (Iran modern) yang menganut Syiah Islam dan menciptakan budaya dan seni Persia yang kaya. Safavid dikenal dengan karpet halus, keramik, dan arsitektur istana megah.",
        periode: "1501-1736",
        kata_kunci: "safavid, persia, iran, syiah",
        wilayah: "Persia (Iran modern)",
        tokoh_penting: ["Ismail I", "Abbas I the Great", "Tahmasp I"],
        dampak: "Seni dan keramik Safavid berkualitas tinggi, arsitektur istana Isfahan, Syiah menjadi dominan di Persia",
        penyebab: "Konsolidasi kekuasaan, adopsi Syiah Islam, ambisi budaya dan artistik",
        akibat: "Jatuh ke Afghani, warisan budaya dan seni Persia bertahan hingga kini",
        sumber_referensi: ["The Safavid Empire", "Persian Art and Culture"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Era Victoria",
        deskripsi_sejarah: "Era Victoria (1837-1901) adalah periode panjang pemerintahan Ratu Victoria di Inggris, ditandai dengan ekspansi Kekaisaran Britania, revolusi industri, dan kemajuan budaya. Era ini melihat Inggris menjadi kekuatan hegemoni global dengan pengaruh di seluruh dunia.",
        periode: "1837-1901",
        kata_kunci: "victoria, inggris, era, kekaisaran, industri",
        wilayah: "Inggris, Kekaisaran Britania (global)",
        tokoh_penting: ["Queen Victoria", "Prime Minister Disraeli", "Prime Minister Gladstone", "Prince Albert"],
        dampak: "Ekspansi Kekaisaran Britania, revolusi industri mencapai puncak, budaya Victorian yang kaya",
        penyebab: "Stabilitas pemerintahan, kekuatan ekonomi Inggris, ambisi imperialisme",
        akibat: "Fondasi hegemoni Britania, pengaruh budaya Inggris global, era yang berakhir dengan kematian Victoria",
        sumber_referensi: ["Queen Victoria", "The Victorian Era: An Illustrated History"],
        kategori: "Era Historis"
      },
      {
        judul_sejarah: "Perang Dingin",
        deskripsi_sejarah: "Perang Dingin (1947-1991) adalah periode ketegangan geopolitik antara Amerika Serikat dan Uni Soviet setelah Perang Dunia II. Meskipun tidak ada perang langsung antara keduanya, persaingan ideologi, perlombaan senjata nuklir, dan konflik proxy di seluruh dunia mendefinisikan era ini.",
        periode: "1947-1991",
        kata_kunci: "dingin, perang, soviet, usa, nuclear",
        wilayah: "Global (fokus Eropa, Asia, Amerika)",
        tokoh_penting: ["Dwight D. Eisenhower", "John F. Kennedy", "Nikita Khrushchev", "Mikhail Gorbachev"],
        dampak: "Perlombaan senjata nuklir, polarisasi ideologi, pembentukan NATO dan Blok Timur, Perang Korea dan Vietnam",
        penyebab: "Perbedaan ideologi komunis vs kapitalisme, perlawanan terhadap ekspansi Soviet, ambisi hegemoni global",
        akibat: "Runtuhnya Uni Soviet 1991, akhir Perang Dingin, keunggulan Amerika sebagai satu-satunya superpower",
        sumber_referensi: ["The Cold War: A New History", "Architects of the Cold War"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Perang Tiga Puluh Tahun",
        deskripsi_sejarah: "Perang Tiga Puluh Tahun (1618-1648) adalah konflik religius dan politikus di Eropa Tengah yang menghancurkan wilayah besar dan populasinya. Perang ini melibatkan kekuatan-kekuatan besar seperti Spanyol, Prancis, dan Swedia dalam perjuangan atas hegemoni Eropa.",
        periode: "1618-1648",
        kata_kunci: "perang, eropa, religius, tiga puluh tahun",
        wilayah: "Eropa Tengah, Jerman, Bohemia",
        tokoh_penting: ["Gustavus Adolphus", "Cardinal Richelieu", "Wallenstein", "Fernando II"],
        dampak: "Perjanjian Westphalia, sistem negara-bangsa modern, berkurangnya kekuatan Kekaisaran Romawi Suci",
        penyebab: "Ketegangan religius Protestan-Katolik, persaingan kerajaan, ambisi hegemoni di Eropa",
        akibat: "Jutaan korban, 1/3 populasi Jerman tewas, kesepakatan damai Westphalia",
        sumber_referensi: ["The Thirty Years War", "Peace of Westphalia by Thomas Munck"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Perang Kemerdekaan Indonesia",
        deskripsi_sejarah: "Perang Kemerdekaan Indonesia (1945-1949) adalah perjuangan rakyat Indonesia untuk melepaskan diri dari penjajahan Belanda setelah proklamasi kemerdekaan 17 Agustus 1945. Perang ini melibatkan pertempuran militer, diplomasi internasional, dan pengakuan kedaulatan Indonesia.",
        periode: "1945-1949",
        kata_kunci: "indonesia, kemerdekaan, perjuangan, belanda",
        wilayah: "Indonesia, Nusantara",
        tokoh_penting: ["Sukarno", "Muhammad Hatta", "Soekarno", "Jenderal Sudirman", "Sutan Sjahrir"],
        dampak: "Pengakuan kemerdekaan Indonesia, pembentukan negara-bangsa, inspirasi dekolonisasi global",
        penyebab: "Penjajahan Belanda 350 tahun, kesadaran nasional, Perang Dunia II",
        akibat: "Indonesia merdeka, negara baru di Asia Tenggara, anggota PBB",
        sumber_referensi: ["Sejarah Indonesia", "Indonesian Independence by M.C. Ricklefs"],
        kategori: "Revolusi"
      },
      {
        judul_sejarah: "Revolusi Cina 1949",
        deskripsi_sejarah: "Revolusi Cina 1949 adalah kemenangan Partai Komunis Cina di bawah Mao Zedong atas Kuomintang (Nasionalis Cina), mendirikan Republik Rakyat Cina. Revolusi ini mengubah lanskap geopolitik Asia dan menjadi tonggak penting dalam sejarah abad ke-20.",
        periode: "1949",
        kata_kunci: "cina, komunis, mao, revolusi",
        wilayah: "Tiongkok, Asia Timur",
        tokoh_penting: ["Mao Zedong", "Zhou Enlai", "Deng Xiaoping", "Chiang Kai-shek"],
        dampak: "Pembentukan Cina komunis, penolakan Taiwan, transformasi Cina menjadi negara industri",
        penyebab: "Perang Sipil Cina, kekalahan Kuomintang, dukungan rakyat untuk reformasi",
        akibat: "Cina menjadi superpower komunis, perpindahan Kuomintang ke Taiwan, Perang Korea",
        sumber_referensi: ["The Chinese Revolution", "Mao: A Life by Philip Short"],
        kategori: "Revolusi"
      },
      {
        judul_sejarah: "Krisis Kuba",
        deskripsi_sejarah: "Krisis Kuba (1962) adalah episode konfrontasi paling berbahaya Perang Dingin ketika Amerika Serikat dan Uni Soviet hampir berperang atas pemasangan rudal Soviet di Kuba. Krisis ini berlangsung 13 hari dan menjadi momen terdekat dengan perang nuklir.",
        periode: "1962",
        kata_kunci: "kuba, krisis, nuklir, soviet, usa",
        wilayah: "Kuba, Karibia, Samudra Atlantik",
        tokoh_penting: ["John F. Kennedy", "Nikita Khrushchev", "Fidel Castro", "Robert F. Kennedy"],
        dampak: "Pemahaman bahaya perang nuklir, pembentukan jalur komunikasi darurat (hotline) antara superpower",
        penyebab: "Revolusi Kuba, kegagalan Bay of Pigs, kekhawatiran Amerika atas ekspansi Soviet",
        akibat: "Penarikan rudal Soviet dari Kuba, perjanjian non-proliferasi nuklir dimulai",
        sumber_referensi: ["The Cuban Missile Crisis", "Thirteen Days by Robert F. Kennedy"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Pendaratan di Bulan",
        deskripsi_sejarah: "Pendaratan di Bulan (1969) adalah pencapaian luar biasa ketika manusia pertama kali mendarat di Bulan. Astronot Apollo 11 Neil Armstrong dan Buzz Aldrin berhasil pendaratan, mengumpulkan sampel batu bulan, dan mengubah pemahaman manusia tentang ruang angkasa.",
        periode: "1969",
        kata_kunci: "bulan, apollo, ruang angkasa, armstrong",
        wilayah: "Bulan, ruang angkasa",
        tokoh_penting: ["Neil Armstrong", "Buzz Aldrin", "Michael Collins", "Wernher von Braun"],
        dampak: "Pencapaian teknologi luar angkasa, inspirasi untuk eksplorasi masa depan, bukti kemampuan teknologi manusia",
        penyebab: "Perlombaan ruang angkasa Perang Dingin, ambisi ilmiah, program Apollo NASA",
        akibat: "Langkah besar bagi kemanusiaan, penelitian bulan, fondasi eksplorasi ruang angkasa modern",
        sumber_referensi: ["A Man on the Moon", "The Right Stuff by Tom Wolfe"],
        kategori: "Pencapaian Ilmiah"
      },
      {
        judul_sejarah: "Perang Vietnam",
        deskripsi_sejarah: "Perang Vietnam (1955-1975) adalah perang panjang antara Vietnam Utara (didukung Soviet) dan Vietnam Selatan (didukung Amerika), berevolusi menjadi perang proxy dalam Perang Dingin. Perang ini menyebabkan jutaan korban dan perubahan dalam persepsi tentang perang modern.",
        periode: "1955-1975",
        kata_kunci: "vietnam, perang, proxy, perang dingin",
        wilayah: "Vietnam, Kamboja, Laos, Asia Tenggara",
        tokoh_penting: ["Ho Chi Minh", "Lyndon B. Johnson", "Richard Nixon", "General William Westmoreland"],
        dampak: "Penyatuan Vietnam di bawah komunis, trauma Amerika, perubahan strategi militer, gerakan anti-perang",
        penyebab: "Dekolonisasi Indochina, Perang Dingin, konflik ideologi komunis vs kapitalisme",
        akibat: "Kekalahan Amerika, penyatuan Vietnam, pengungsi Vietnam ke seluruh dunia",
        sumber_referensi: ["The Vietnam War", "A Bright Shining Lie by Neil Sheehan"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Tsunami Samudra Hindia 2004",
        deskripsi_sejarah: "Tsunami Samudra Hindia 2004 adalah bencana alam terburuk dalam sejarah modern yang terjadi setelah gempa bumi dahsyat 9.1 skala Richter. Tsunami menghancurkan pesisir di Indonesia, Thailand, India, dan negara-negara lain, menewaskan lebih dari 230,000 orang.",
        periode: "2004",
        kata_kunci: "tsunami, bencana alam, gempa, hindia",
        wilayah: "Samudra Hindia, Indonesia, Thailand, India, Somalia",
        tokoh_penting: ["Ilmuwan seismologi dunia", "Tim penyelamat internasional"],
        dampak: "Kesadaran bencana alam global, sistem peringatan tsunami, kerja sama kemanusiaan internasional",
        penyebab: "Gempa bumi 9.1 Richter di Aceh, pergeseran lempeng tektonik",
        akibat: "230,000+ kematian, kerusakan ekonomi besar, program pembangunan kembali",
        sumber_referensi: ["The Last Tsunami", "2004 Indian Ocean Earthquake Documentation"],
        kategori: "Bencana Alam"
      },
      {
        judul_sejarah: "Peradaban Fenisia",
        deskripsi_sejarah: "Peradaban Fenisia (1500 SM - 332 SM) adalah peradaban maritim kuno yang terkenal sebagai pedagang dan penjelajah laut terbaik di Mediterania. Fenisia menciptakan abjad pertama (akar alfabet modern) dan mendirikan koloni di seluruh Mediterania.",
        periode: "1500 SM - 332 SM",
        kata_kunci: "fenisia, maritim, pedagang, alfabet",
        wilayah: "Levant, Mediterania, Utara Afrika",
        tokoh_penting: ["Raja Hiram I", "Hannibal", "Dido"],
        dampak: "Abjad Fenisia menjadi dasar alfabet Yunani dan Latin, perdagangan Mediterania, eksplorasi maritim",
        penyebab: "Posisi geografis Levant, kurangnya lahan pertanian, keunggulan maritim",
        akibat: "Ditaklukkan Alexander Agung, warisan alfabet bertahan hingga kini",
        sumber_referensi: ["The Phoenicians", "Hannibal's Triumph by Robert Brice"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Kerajaan Nubia",
        deskripsi_sejarah: "Kerajaan Nubia (2500 SM - 400 M) adalah kerajaan kuno di Afrika Timur Laut, di sepanjang Sungai Nil. Nubia memiliki peradaban maju dengan piramida mereka sendiri, perdagangan yang kaya, dan sering berinteraksi dengan Mesir Kuno.",
        periode: "2500 SM - 400 M",
        kata_kunci: "nubia, sudan, afrika, piramida",
        wilayah: "Sudan modern, Afrika Timur Laut",
        tokoh_penting: ["Piankhi", "Shabaka", "Tutankhamun (hubungan)"],
        dampak: "Perdagangan Afrika-Timur Tengah, seni dan arsitektur Nubia, pengaruh budaya pada Mesir",
        penyebab: "Posisi geografis strategis di Sungai Nil, sumber daya alam",
        akibat: "Invasi Aksumite, transformasi budaya Afrika",
        sumber_referensi: ["Nubia: Kingdom of the Sun", "The Civilizations of the Nubians"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Kerajaan Aksumite",
        deskripsi_sejarah: "Kerajaan Aksumite (100 M - 940 M) adalah kerajaan besar di Tanduk Afrika yang rivalisasi dengan Kekaisaran Romawi dan Persia. Aksumite mencapai puncak kekuasaan dengan mengontrol perdagangan laut Merah dan menganut Kekristenan Koptik.",
        periode: "100 M - 940 M",
        kata_kunci: "aksumite, ethiopia, kerajaan, kekristenan",
        wilayah: "Tanduk Afrika, Ethiopia, Eritrea",
        tokoh_penting: ["Raja Ezana", "Raja Abreha", "Yohannae"],
        dampak: "Penyebaran Kekristenan di Afrika, perdagangan laut Merah, pengaruh pada Ethiopia modern",
        penyebab: "Posisi geografis strategis, konversi ke Kekristenan, kekuatan militer",
        akibat: "Jatuh ke ekspansi Arab Islam, warisan gereja Koptik di Ethiopia",
        sumber_referensi: ["The Kingdom of Aksum", "Ancient African Kingdoms"],
        kategori: "Kerajaan"
      },
      {
        judul_sejarah: "Kerajaan Seljuk",
        deskripsi_sejarah: "Kerajaan Seljuk (1037-1194) adalah kerajaan Turki besar yang mendominasi Timur Tengah dan Persia, mempromosikan seni, sastra, dan arsitektur Islam yang kaya. Seljuk menciptakan epos seni dan budaya Islam di era emas mereka.",
        periode: "1037-1194",
        kata_kunci: "seljuk, turki, islam, timur tengah",
        wilayah: "Timur Tengah, Persia, Asia Kecil",
        tokoh_penting: ["Alp Arslan", "Nizam al-Mulk", "Malik Shah"],
        dampak: "Kemajuan seni dan arsitektur Islam, penyebaran Islam, inovasi budaya",
        penyebab: "Migrasi Turk dari Asia Tengah, ekspansi militer, adopsi Islam",
        akibat: "Fragmentasi menjadi Seljuk Rum dan Seljuk Persia, pengaruh pada kerajaan Ottoman",
        sumber_referensi: ["The Seljuks", "Islamic Art and Architecture"],
        kategori: "Kerajaan"
      },
      {
        judul_sejarah: "Kesultanan Delhi",
        deskripsi_sejarah: "Kesultanan Delhi (1206-1526) adalah kesultanan Islam besar di Asia Selatan yang memerintah India Utara dan Tengah selama 320 tahun. Delhi Sultanate menciptakan perpaduan budaya Hindu-Muslim dan arsitektur yang indah.",
        periode: "1206-1526",
        kata_kunci: "delhi, sultanat, islam, india",
        wilayah: "India, Asia Selatan",
        tokoh_penting: ["Qutb-ud-din Aibak", "Muhammad of Ghor", "Alauddin Khilji", "Zia ud-Din Barani"],
        dampak: "Arsitektur Indo-Islamic, Qutab Minar, administrasi yang terorganisir, budaya Muslim di India",
        penyebab: "Invasi dari Asia Tengah, penaklukan militer, ambisi ekspansi",
        akibat: "Jatuh ke Mughal, warisan budaya Hindu-Muslim bertahan",
        sumber_referensi: ["The Delhi Sultanate", "Islamic Empires in India"],
        kategori: "Kesultanan"
      },
      {
        judul_sejarah: "Revolusi Glorious (Inggris)",
        deskripsi_sejarah: "Revolusi Glorious (1688) adalah pergantian dinasti di Inggris tanpa pertumpahan darah yang signifikan, menggantikan Raja James II dengan William III dan Mary II. Revolusi ini menetapkan kekuasaan parlemen dan hak-hak kebebasan sipil.",
        periode: "1688",
        kata_kunci: "glorious, revolusi, inggris, parlemen",
        wilayah: "Inggris, Skotlandia, Irlandia",
        tokoh_penting: ["William III", "James II", "Mary II", "Edmund Burke"],
        dampak: "Pembentukan monarki konstitusional, Bill of Rights, supremasi parlemen, fondasi demokrasi modern",
        penyebab: "Ketidaksenangan terhadap James II, ketakutan atas paganisme, ambisi William of Orange",
        akibat: "Inggris menjadi monarki konstitusional, fondasi untuk Inggris modern",
        sumber_referensi: ["The Glorious Revolution", "1688 and All That by Edmund Burke"],
        kategori: "Revolusi"
      },
      {
        judul_sejarah: "Era Heian (Jepang)",
        deskripsi_sejarah: "Era Heian (794-1185) adalah era emas budaya Jepang dengan perkembangan seni, literatur, dan arsitektur yang luar biasa. Periode ini melihat berkembangnya budaya Jepang yang unik melalui seni kaligrafi, puisi, dan drama Noh.",
        periode: "794-1185",
        kata_kunci: "heian, jepang, budaya, seni",
        wilayah: "Jepang",
        tokoh_penting: ["Kanmu Emperor", "Sugawara no Michizane", "Murasaki Shikibu", "Sei Shonagon"],
        dampak: "Seni dan budaya Jepang berkembang, literatur klasik Jepang, arsitektur tradisional Jepang",
        penyebab: "Stabilitas pemerintahan, kemakmuran ekonomi, pengaruh Tiongkok berkurang",
        akibat: "Perkembangan budaya Jepang unik, fondasi tradisi Jepang modern",
        sumber_referensi: ["The Heian Period", "Japanese Culture and Tradition"],
        kategori: "Era Budaya"
      },
      {
        judul_sejarah: "Era Sengoku (Jepang)",
        deskripsi_sejarah: "Era Sengoku (1467-1603) adalah periode chaos dan peperangan di Jepang ketika daimyo lokal bersaing untuk kontrol, dikenal sebagai 'periode negara yang berperang'. Periode ini akhirnya diselesaikan oleh Tokugawa Ieyasu.",
        periode: "1467-1603",
        kata_kunci: "sengoku, jepang, perang, daimyo",
        wilayah: "Jepang",
        tokoh_penting: ["Oda Nobunaga", "Toyotomi Hideyoshi", "Tokugawa Ieyasu", "Takeda Shingen"],
        dampak: "Unifikasi Jepang, perkembangan seni perang (bushido), fondasi Periode Edo",
        penyebab: "Jatuhnya kekuasaan shogun Ashikaga, persaingan daimyo, kelaparan",
        akibat: "Penyatuan Jepang, Periode Edo yang stabil",
        sumber_referensi: ["The Sengoku Period", "The Samurai Code"],
        kategori: "Era Historis"
      },
      {
        judul_sejarah: "Perang Napoleonik Ekspansi ke Mesir",
        deskripsi_sejarah: "Kampanye Mesir Napoleon (1798-1801) adalah upaya menaklukkan Mesir dan membuka jalan ke India. Kampanye ini berakhir dengan kegagalan tetapi menghasilkan penemuan Batu Rosetta yang penting untuk memahami hieroglif Mesir.",
        periode: "1798-1801",
        kata_kunci: "napoleon, mesir, kampanye, batu rosetta",
        wilayah: "Mesir, Timur Tengah",
        tokoh_penting: ["Napoleon Bonaparte", "General Desaix", "Admiral Nelson"],
        dampak: "Penemuan Batu Rosetta, pemahaman hieroglif Mesir, eksplorasi arkeologi",
        penyebab: "Ambisi Napoleon untuk ekspansi, keinginan mengalahkan Inggris",
        akibat: "Kekalahan oleh armada Inggris, penarikan dari Mesir, Mesir tetap Ottoman",
        sumber_referensi: ["Napoleon in Egypt", "The Rosetta Stone Mystery"],
        kategori: "Kampanye Militer"
      },
      {
        judul_sejarah: "Perjanjian Traktat de Tordesillas",
        deskripsi_sejarah: "Perjanjian Tordesillas (1494) adalah perjanjian antara Spanyol dan Portugal yang membagi dunia baru menjadi dua zona pengaruh. Perjanjian ini menghasilkan eksplorasi dan kolonialisasi Amerika dan wilayah lain oleh dua kekuatan ini.",
        periode: "1494",
        kata_kunci: "tordesillas, spanyol, portugal, eksplorasi",
        wilayah: "Global (terutama Amerika)",
        tokoh_penting: ["Pope Alexander VI", "Ferdinand of Spain", "Manuel I of Portugal"],
        dampak: "Pembagian dunia baru, eksplorasi dan kolonialisasi Eropa, dasar imperialisme Eropa",
        penyebab: "Eksplorasi Kristen, ambisi ekspansi, mediasi Paus",
        akibat: "Spanyol mendapat Amerika, Portugal mendapat Brasil dan Asia, transformasi global",
        sumber_referensi: ["The Treaty of Tordesillas", "European Expansion and Colonization"],
        kategori: "Perjanjian Historis"
      },
      {
        judul_sejarah: "Perang Seratus Tahun",
        deskripsi_sejarah: "Perang Seratus Tahun (1337-1453) adalah serangkaian perang antara Kerajaan Inggris dan Prancis atas kontrol tanah di Perancis. Perang ini menjadi salah satu perang terlama di Eropa dengan konsekuensi besar bagi kedua negara.",
        periode: "1337-1453",
        kata_kunci: "seratus, tahun, perang, inggris, prancis",
        wilayah: "Prancis, Inggris",
        tokoh_penting: ["Edward III", "Henry V", "Joan of Arc", "Charles VII"],
        dampak: "Pembentukan identitas nasional Prancis dan Inggris, kemenangan Prancis, akhir periode Abad Pertengahan",
        penyebab: "Suksesi Prancis, klaim Inggris atas tanah Perancis, persaingan feodal",
        akibat: "Kemenangan Prancis, Inggris kehilangan tanah di Perancis, peningkatan nasionalisme",
        sumber_referensi: ["The Hundred Years War", "Joan of Arc and the Hundred Years War"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Abad Pencerahan Islam (Abad Ke-8 - 11)",
        deskripsi_sejarah: "Abad Pencerahan Islam adalah periode perkembangan ilmu pengetahuan dan budaya Islam yang luar biasa. Tokoh-tokoh seperti Al-Kwarizmi, Al-Razi, Ibn Sina, dan Al-Ghazali menciptakan karya-karya besar dalam matematika, sains, medis, dan filsafat.",
        periode: "750 M - 1100 M",
        kata_kunci: "islam, pencerahan, sains, matematika",
        wilayah: "Dunia Islam, Timur Tengah, Persia, Afrika Utara",
        tokoh_penting: ["Al-Khwarizmi", "Al-Razi", "Ibn Sina", "Al-Ghazali", "Al-Farabi"],
        dampak: "Kemajuan sains dan matematika, aljabar dan algoritma, pengaruh pada Renaisans Eropa",
        penyebab: "Dinasti Abbasiyah yang stabil, perlindungan terhadap cendekiawan, terjemahan karya Yunani",
        akibat: "Pengaruh pada ilmu pengetahuan Barat, warisan ilmiah hingga kini",
        sumber_referensi: ["The House of Wisdom", "Islamic Science and Mathematics"],
        kategori: "Era Emas Islam"
      },
      {
        judul_sejarah: "Peradaban Cahokia",
        deskripsi_sejarah: "Peradaban Cahokia (600-1400 M) adalah peradaban Mississippi Pra-Columbus terbesar di Amerika Utara dengan kota besar Cahokia. Kota ini mencapai populasi 10,000-20,000 orang dan memiliki monumen besar Monks Mound.",
        periode: "600-1400 M",
        kata_kunci: "cahokia, mississippi, peradaban, monks mound",
        wilayah: "Amerika Utara, sungai Mississippi",
        tokoh_penting: ["Penduduk Cahokia Pra-Columbus"],
        dampak: "Bukit megah (Monks Mound), sistem perdagangan, kota terorganisir Pra-Columbus",
        penyebab: "Pertanian maju, posisi geografis strategis, pertumbuhan populasi",
        akibat: "Runtuh misterius, ditinggalkan sebelum kedatangan Eropa",
        sumber_referensi: ["Cahokia: Moundbuilders of the Mississippi", "Pre-Columbian North America"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Peradaban Nabataean",
        deskripsi_sejarah: "Peradaban Nabataean (4 SM - 106 M) adalah masyarakat Arab kuno yang menguasai perdagangan rempah di Timur Tengah. Nabataean terkenal dengan kota Petra yang dibangun dalam batu merah dan sistem perdagangan yang canggih.",
        periode: "4 SM - 106 M",
        kata_kunci: "nabataean, petra, perdagangan, rempah",
        wilayah: "Timur Tengah, Yordania, Arab",
        tokoh_penting: ["Aretas III", "Aretas IV"],
        dampak: "Petra arsitektur megah, perdagangan rempah yang kaya, pengaruh budaya",
        penyebab: "Posisi geografis strategis, kontrol jalur perdagangan rempah",
        akibat: "Ditaklukkan Romawi, pengaruh pada budaya Arab",
        sumber_referensi: ["The Nabataeans", "Petra: Rose City of the Desert"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Kerajaan Khwarezm",
        deskripsi_sejarah: "Kerajaan Khwarezm (6 SM - 1097 M) adalah kerajaan kuno di Asia Tengah yang kaya dengan perdagangan rempah dan budaya yang berkembang. Khwarezm menciptakan sistem irigasi canggih dan menjadi pusat pembelajaran Islam.",
        periode: "6 SM - 1097 M",
        kata_kunci: "khwarezm, asia tengah, rempah, perdagangan",
        wilayah: "Asia Tengah, sepanjang Sungai Amu Darya",
        tokoh_penting: ["Al-Khwarezmi", "Raja Khwarezm"],
        dampak: "Pusat pembelajaran, inovasi irigasi, kontribusi pada pemahaman matematika",
        penyebab: "Posisi geografis strategis, pertanian yang berkembang",
        akibat: "Penaklukan Mongol, transformasi budaya",
        sumber_referensi: ["The Khwarezm Kingdom", "Islamic Central Asia"],
        kategori: "Kerajaan"
      },
      {
        judul_sejarah: "Dinasti Fatimid",
        deskripsi_sejarah: "Dinasti Fatimid (909-1171) adalah dinasti Syiah besar yang menguasai Afrika Utara, Mesir, dan Levant. Fatimid menciptakan Kota Kairo dan menjadi pusat keagamaan dan budaya Islam yang penting.",
        periode: "909-1171",
        kata_kunci: "fatimid, syiah, mesir, kairo",
        wilayah: "Afrika Utara, Mesir, Levant",
        tokoh_penting: ["Al-Mahdi", "Al-Aziz", "Saladin (penghancur)"],
        dampak: "Pembangunan Kairo, Al-Azhar University, seni dan arsitektur Fatimid",
        penyebab: "Klaim keturunan Fatimah (putri Prophet Muhammad), ekspansi militer",
        akibat: "Ditaklukkan Saladin dan Dinasti Ayyubid, warisan budaya bertahan",
        sumber_referensi: ["The Fatimid Dynasty", "Islamic Cairo by Max Rodenbeck"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Dinasti Ayyubid",
        deskripsi_sejarah: "Dinasti Ayyubid (1169-1260) adalah dinasti Islam yang didirikan oleh Saladin setelah menguasai Mesir. Dinasti ini menguasai Mesir, Levant, dan Mesopotamia, terkenal dengan Saladin dan Perang Salib.",
        periode: "1169-1260",
        kata_kunci: "ayyubid, saladin, islam, perang salib",
        wilayah: "Mesir, Levant, Mesopotamia",
        tokoh_penting: ["Saladin", "Al-Kamil", "Al-Malik al-Adil"],
        dampak: "Pemulihan Yerusalem dari Kristen, arsitektur Islam megah, reformasi militer",
        penyebab: "Kekhawatiran terhadap Perang Salib, ambisi Saladin",
        akibat: "Ditaklukkan Mamluk, warisan Saladin terkenal di Barat dan Islam",
        sumber_referensi: ["Saladin and the Crusades", "The Ayyubid Dynasty"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Peradaban Göktürk",
        deskripsi_sejarah: "Peradaban Göktürk (550-745 M) adalah kerajaan Turk kuno di Asia Tengah yang menguasai jalur sutra. Göktürk menciptakan sistem suku-suku terorganisir dan berinteraksi dengan Kekaisaran Tiongkok.",
        periode: "550-745 M",
        kata_kunci: "goktürk, turk, asia tengah, jalur sutra",
        wilayah: "Asia Tengah, Mongolia, Tiongkok Utara",
        tokoh_penting: ["Bumin Khan", "Istemi Khan", "Bilge Khan"],
        dampak: "Kontrol jalur sutra, perdagangan Asia, pengaruh pada sejarah Turk",
        penyebab: "Unifikasi suku-suku Turk, ambisi ekspansi",
        akibat: "Jatuh ke ekspansi Tang Cina, warisan Turk di Asia Tengah",
        sumber_referensi: ["The Göktürks", "The History of the Turks"],
        kategori: "Kerajaan"
      },
      {
        judul_sejarah: "Kerajaan Tocharian",
        deskripsi_sejarah: "Kerajaan Tocharian (2000 SM - 900 M) adalah peradaban IndoEuropean kuno di Tiongkok Barat. Tocharian menciptakan budaya unik yang menggabungkan pengaruh IndoEuropean dan Tiongkok.",
        periode: "2000 SM - 900 M",
        kata_kunci: "tocharian, indoeuropean, tiongkok barat",
        wilayah: "Tiongkok Barat (Xinjiang), Asia Tengah",
        tokoh_penting: ["Penduduk Tocharian"],
        dampak: "Bukti migrasi IndoEuropean, perpaduan budaya Timur-Barat",
        penyebab: "Migrasi dari Eropa, posisi geografis di jalur sutra",
        akibat: "Asimilasi dengan budaya Tiongkok, warisan budaya hilang",
        sumber_referensi: ["The Tocharians", "The Silk Road and IndoEuropean Peoples"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Penjajahan Britania Raya atas India",
        deskripsi_sejarah: "Penjajahan Inggris atas India (1757-1947) adalah periode kontrol Inggris atas subbenua India yang berlangsung hampir 200 tahun. Periode ini ditandai dengan eksploitasi ekonomi, transformasi sosial, dan akhirnya Gerakan Kemerdekaan India.",
        periode: "1757-1947",
        kata_kunci: "inggris, india, penjajahan, kemerdekaan",
        wilayah: "India, Pakistan, Bangladesh, Asia Selatan",
        tokoh_penting: ["Lord Clive", "Queen Victoria", "Mahatma Gandhi", "Jawaharlal Nehru"],
        dampak: "Industrialisasi India, sistem kereta api, pendidikan Inggris, gerakan kemerdekaan",
        penyebab: "Kekuatan militer Britania, perdagangan rempah, ambisi ekspansi imperial",
        akibat: "Kemerdekaan India 1947, pembagian India-Pakistan, warisan budaya hybrid",
        sumber_referensi: ["The British Raj", "India: A Very Short Introduction"],
        kategori: "Penjajahan"
      },
      {
        judul_sejarah: "Revolusi Ruang Angkasa",
        deskripsi_sejarah: "Revolusi Ruang Angkasa (1957-1970an) adalah era perlombaan luar angkasa antara Amerika Serikat dan Uni Soviet selama Perang Dingin. Era ini ditandai dengan peluncuran satelit, perjalanan manusia ke luar angkasa, dan pendaratan bulan.",
        periode: "1957-1970an",
        kata_kunci: "ruang, angkasa, satelit, apollo, sputnik",
        wilayah: "Global, ruang angkasa",
        tokoh_penting: ["Wernher von Braun", "Sergei Korolev", "Neil Armstrong", "Yuri Gagarin"],
        dampak: "Teknologi satelit modern, sistem GPS, komunikasi global, pemahaman baru tentang ruang",
        penyebab: "Perlombaan Perang Dingin, ambisi teknologi, ambisi ilmiah",
        akibat: "Satelit, teknologi telekomunikasi, pendaratan bulan, eksplorasi antarplanet",
        sumber_referensi: ["The Rocket Age", "Apollo 13 by Jim Lovell"],
        kategori: "Revolusi Teknologi"
      },
      {
        judul_sejarah: "Gerakan Hak Asasi Manusia 1960an",
        deskripsi_sejarah: "Gerakan Hak Asasi Manusia 1960an adalah gerakan sosial global untuk kesetaraan ras, gender, dan hak sipil. Dipimpin oleh tokoh seperti Martin Luther King Jr., Malcolm X, dan Rosa Parks di Amerika, gerakan ini mengubah perspektif sosial.",
        periode: "1960-1975",
        kata_kunci: "hak asasi, civil rights, martin luther king, kesetaraan",
        wilayah: "Amerika Serikat, global",
        tokoh_penting: ["Martin Luther King Jr.", "Rosa Parks", "Malcolm X", "Gloria Steinem"],
        dampak: "Perundangan hak sipil, kesetaraan ras dan gender, aktivisme sosial global",
        penyebab: "Diskriminasi rasial, ketidakadilan sosial, inspirasi dari gerakan dekolonisasi",
        akibat: "Undang-undang Hak Sipil, perubahan perspektif sosial, gerakan feminis modern",
        sumber_referensi: ["The Civil Rights Movement", "I Have a Dream Speech"],
        kategori: "Gerakan Sosial"
      },
      {
        judul_sejarah: "Peradaban Cahokia Moundbuilders",
        deskripsi_sejarah: "Peradaban Cahokia Moundbuilders (600-1400 M) adalah peradaban Mississippi Pra-Columbus terbesar di Amerika Utara dengan sistem kota kompleks dan monumen besar.",
        periode: "600-1400 M",
        kata_kunci: "cahokia, moundbuilders, mississippi, peradaban",
        wilayah: "Amerika Utara, Sungai Mississippi",
        tokoh_penting: ["Penduduk Cahokia Pra-Columbus"],
        dampak: "Monks Mound (monumen terbesar Pra-Columbus di Amerika Utara), sistem perdagangan",
        penyebab: "Pertanian maju, posisi geografis strategis",
        akibat: "Runtuh misterius, ditinggalkan sebelum kedatangan Eropa",
        sumber_referensi: ["Cahokia: City of the Sun", "Pre-Columbian America"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Kesultanan Bayezid Ottoman",
        deskripsi_sejarah: "Kesultanan Bayezid Ottoman (1481-1512) adalah periode ekspansi dan stabilisasi Kekaisaran Ottoman di bawah Sultan Bayezid II. Periode ini melihat pertumbuhan kekuatan Ottoman dan konsolidasi wilayah.",
        periode: "1481-1512",
        kata_kunci: "bayezid, ottoman, kesultanan, ekspansi",
        wilayah: "Kekaisaran Ottoman, Turki, Balkans, Timur Tengah",
        tokoh_penting: ["Bayezid II", "Mehmed II (ayah)", "Suleiman (anak)"],
        dampak: "Ekspansi Ottoman, penerimaan pengungsi Yahudi Spanyol, stabilisasi militer",
        penyebab: "Warisan kekuatan Ottoman, ambisi ekspansi",
        akibat: "Fondasi untuk Suleiman Agung, ekspansi Ottoman berlanjut",
        sumber_referensi: ["Bayezid II and the Ottoman Empire", "The Ottomans"],
        kategori: "Kesultanan"
      },
      {
        judul_sejarah: "Perang Inggris-Belanda",
        deskripsi_sejarah: "Perang Inggris-Belanda (1652-1784) adalah serangkaian empat perang maritim antara Inggris dan Belanda untuk dominasi perdagangan laut dan imperium. Perang-perang ini menjadi kunci untuk memahami era merkantilisme.",
        periode: "1652-1784",
        kata_kunci: "inggris, belanda, perang, maritim",
        wilayah: "Laut Utara, Atlantik, Asia",
        tokoh_penting: ["Oliver Cromwell", "Prince Rupert", "Admiral de Witt"],
        dampak: "Supremasi maritim Inggris, akhir dominasi Belanda, pembentukan imperium Inggris",
        penyebab: "Persaingan perdagangan, ambisi maritime supremacy, ekonomi merkantil",
        akibat: "Kemenangan Inggris, ekspansi imperium Inggris, Belanda fokus ke Asia",
        sumber_referensi: ["The Dutch Wars", "Maritime Supremacy and Trade Wars"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Era Bakumatsu (Jepang)",
        deskripsi_sejarah: "Era Bakumatsu (1853-1868) adalah periode akhir Shogunate Tokugawa dan awal Periode Meiji di Jepang. Era ini ditandai dengan ketegangan antara tradisi dan modernisasi, yang akhirnya menghasilkan Restorasi Meiji.",
        periode: "1853-1868",
        kata_kunci: "bakumatsu, jepang, modernisasi, meiji",
        wilayah: "Jepang",
        tokoh_penting: ["Commodore Perry", "Tokugawa Iemochi", "Meiji Emperor", "Saigō Takamori"],
        dampak: "Akhir feodalism, awal modernisasi Jepang, pembukaan Jepang ke dunia Barat",
        penyebab: "Ketegangan karena keterbukaan dari Barat, kelemahan Shogunate",
        akibat: "Restorasi Meiji, transformasi Jepang menjadi kekuatan modern",
        sumber_referensi: ["Bakumatsu: The Final Years", "Meiji Restoration"],
        kategori: "Era Historis"
      },
      {
        judul_sejarah: "Revolusi Industri Kedua",
        deskripsi_sejarah: "Revolusi Industri Kedua (1870-1914) adalah gelombang kedua industrialisasi dengan teknologi baru seperti listrik, motor internal combustion, dan kimia. Era ini melihat munculnya korporasi besar dan imperialisme industri.",
        periode: "1870-1914",
        kata_kunci: "industri, kedua, listrik, motor, teknologi",
        wilayah: "Eropa, Amerika, global",
        tokoh_penting: ["Thomas Edison", "Nikola Tesla", "Henry Ford", "John D. Rockefeller"],
        dampak: "Listrik dan motor industri, kendaraan bermotor, produksi massal, urbanisasi",
        penyebab: "Penemuan teknologi baru, kebutuhan efisiensi produksi, investasi modal",
        akibat: "Urbanisasi masif, kelas pekerja besar, imperialisme industri, fondasi Perang Dunia I",
        sumber_referensi: ["The Second Industrial Revolution", "The Age of Steam and Steel"],
        kategori: "Revolusi Teknologi"
      },
      {
        judul_sejarah: "Perang Opium",
        deskripsi_sejarah: "Perang Opium (1840-1860) adalah serangkaian perang antara Inggris dan Tiongkok atas perdagangan opium. Perang ini menghasilkan pembukaan pasar Tiongkok untuk perdagangan Barat dan kolonisasi Hong Kong oleh Inggris.",
        periode: "1840-1860",
        kata_kunci: "opium, perang, inggris, tiongkok",
        wilayah: "Tiongkok, Hong Kong, Asia Timur",
        tokoh_penting: ["Lord Macartney", "Lin Zexu", "Queen Victoria"],
        dampak: "Pembukaan pasar Tiongkok, kolonisasi Hong Kong, penurunan prestige Tiongkok",
        penyebab: "Defisit perdagangan Inggris, permintaan opium, imperialisme Barat",
        akibat: "Tiongkok kehilangan kekuatan, era semi-kolonial Tiongkok dimulai",
        sumber_referensi: ["The Opium Wars", "China and the Opium Wars"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Pemberontakan Boxer",
        deskripsi_sejarah: "Pemberontakan Boxer (1899-1901) adalah pemberontakan rakyat Tiongkok terhadap imperialisme Barat dan penjajahan asing. Pemberontakan ini dihancurkan oleh kekuatan Barat gabungan tetapi menunjukkan resistensi Tiongkok terhadap imperialisme.",
        periode: "1899-1901",
        kata_kunci: "boxer, pemberontakan, tiongkok, imperialisme",
        wilayah: "Tiongkok, Beijing",
        tokoh_penting: ["Ci Xi (Empress Dowager)", "General Seymour"],
        dampak: "Kesadaran anti-imperialisme Tiongkok, penghancuran situs bersejarah, ganti rugi besar",
        penyebab: "Ketidakpuasan terhadap imperialisme Barat, kelaparan, krisis sosial",
        akibat: "Penindasan kuat oleh kekuatan Barat, mempercepat keruntuhan Dinasti Qing",
        sumber_referensi: ["The Boxer Rebellion", "China Under Western Domination"],
        kategori: "Pemberontakan"
      },
      {
        judul_sejarah: "Reformasi Tanzimat (Ottoman)",
        deskripsi_sejarah: "Reformasi Tanzimat (1839-1876) adalah serangkaian reformasi modernisasi Kekaisaran Ottoman untuk mencegah kehancuran. Tanzimat mencakup reformasi militer, administratif, dan sosial yang bertujuan menguatkan Ottoman menghadapi Barat.",
        periode: "1839-1876",
        kata_kunci: "tanzimat, ottoman, reformasi, modernisasi",
        wilayah: "Kekaisaran Ottoman, Turki, Balkans",
        tokoh_penting: ["Sultan Mahmud II", "Sultan Abdul-Mejid", "Mustafa Reshid Pasha"],
        dampak: "Modernisasi Ottoman, sistem administratif baru, sentimen nasionalisme",
        penyebab: "Kelemahan Ottoman menghadapi Barat, kekalahan militer",
        akibat: "Modernisasi parsial tetapi tidak cukup, jatuh Ottoman bertahun-tahun kemudian",
        sumber_referensi: ["The Tanzimat Period", "Ottoman Modernization"],
        kategori: "Reformasi"
      },
      {
        judul_sejarah: "Peradaban Cahokia (Monks Mound)",
        deskripsi_sejarah: "Monumen Monks Mound di Cahokia adalah struktur megah dibangun oleh masyarakat Mississippi Pra-Columbus. Monks Mound adalah monumen besar tertua di Amerika Utara, menunjukkan kemampuan teknik dan organisasi masyarakat Pra-Columbus.",
        periode: "900-1100 M",
        kata_kunci: "monks mound, cahokia, monumen, mississippi",
        wilayah: "Amerika Utara, Illinois, Sungai Mississippi",
        tokoh_penting: ["Penduduk Cahokia"],
        dampak: "Monumen Pra-Columbus terbesar, bukti peradaban maju di Amerika Utara",
        penyebab: "Keahlian teknik konstruksi, organisasi sosial kompleks",
        akibat: "Situs arkeologi penting, UNESCO World Heritage Site",
        sumber_referensi: ["Monks Mound and Cahokia", "Pre-Columbian Engineering"],
        kategori: "Monumen Bersejarah"
      },
      {
        judul_sejarah: "Dinasti Hongwu (Tiongkok)",
        deskripsi_sejarah: "Dinasti Hongwu (1368-1398) adalah awal Dinasti Ming di Tiongkok setelah menggulingkan Dinasti Yuan Mongol. Dinasti Hongwu memulai reformasi dan modernisasi yang menjadi fondasi kebesaran Ming.",
        periode: "1368-1398",
        kata_kunci: "hongwu, ming, tiongkok, reformasi",
        wilayah: "Tiongkok",
        tokoh_penting: ["Zhu Yuanzhang (Emperor Hongwu)", "Yongle Emperor (anak)"],
        dampak: "Penghapusan kekuasaan Mongol, reformasi administrasi, fondasi Ming",
        penyebab: "Perlawanan terhadap kekuasaan Mongol, ambisi unifikasi Tiongkok",
        akibat: "Pendirian Dinasti Ming yang stabil dan berkembang",
        sumber_referensi: ["The Hongwu Emperor", "The Ming Dynasty Begins"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Ekspedisi Zheng He",
        deskripsi_sejarah: "Ekspedisi Zheng He (1405-1433) adalah serangkaian perjalanan maritim besar oleh armada Tiongkok Ming di bawah pimpinan laksamana Zheng He. Ekspedisi ini mencapai Afrika dan membuktikan kemampuan maritim Tiongkok.",
        periode: "1405-1433",
        kata_kunci: "zheng he, ekspedisi, tiongkok, maritim",
        wilayah: "Samudera Hindia, Afrika, Timur Tengah",
        tokoh_penting: ["Zheng He", "Emperor Yongle"],
        dampak: "Penyebaran budaya Tiongkok, perdagangan maritim, bukti kecanggihan teknik Tiongkok",
        penyebab: "Ambisi Yongle untuk ekspansi, kemampuan teknik maritim",
        akibat: "Ekspansi Tiongkok dibatasi setelah ekspedisi, isolasi Tiongkok dimulai",
        sumber_referensi: ["1421: The Year China Discovered the World", "Zheng He's Treasure Fleet"],
        kategori: "Eksplorasi Maritim"
      },
      {
        judul_sejarah: "Revolusi Perancis Revolusi Sipil",
        deskripsi_sejarah: "Periode Revolusi Perancis meliputi fase-fase berbeda termasuk konstitusional, teror, dan Direktori. Setiap fase memiliki karakter unik dan dampak berbeda pada masyarakat Perancis dan Eropa.",
        periode: "1789-1799",
        kata_kunci: "perancis, revolusi, teror, direktori",
        wilayah: "Perancis, Eropa",
        tokoh_penting: ["Robespierre", "Danton", "Marat", "Napoleon"],
        dampak: "Transformasi sosial, deklarasi hak asasi, inspirasi global",
        penyebab: "Ketidakpuasan sosial, krisis ekonomi, ide Pencerahan",
        akibat: "Naik turunnya fase revolusioner, akhirnya Napoleon mengambil alih",
        sumber_referensi: ["The French Revolution Phases", "Citizens by Simon Schama"],
        kategori: "Revolusi"
      },
      {
        judul_sejarah: "Perang Austro-Prusia",
        deskripsi_sejarah: "Perang Austro-Prusia (1866) adalah perang singkat antara Prusia dan Austria atas dominasi di Jerman. Kemenangan Prusia mengakhiri hegemoni Austria di Jerman dan paved way untuk unifikasi Jerman di bawah Prusia.",
        periode: "1866",
        kata_kunci: "austro, prusia, perang, jerman",
        wilayah: "Jerman, Austria",
        tokoh_penting: ["Otto von Bismarck", "Kaiser Wilhelm I", "Franz Joseph I"],
        dampak: "Supremasi Prusia di Jerman, unifikasi Jerman dimulai, perubahan peta Eropa",
        penyebab: "Persaingan untuk dominasi Jerman, ambisi Prusia",
        akibat: "Penguasaan Prusia, penolakan Austria dari Jerman, path menuju unifikasi",
        sumber_referensi: ["The Austro-Prussian War", "Bismarck and German Unification"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Perang Prancis-Prusia",
        deskripsi_sejarah: "Perang Prancis-Prusia (1870-1871) adalah perang antara Prusia (dan sekutu Jerman) dengan Perancis yang menghasilkan kemenangan Prusia dan unifikasi Jerman. Perang ini mengubah peta Eropa dan menyebabkan rasa dendam Perancis.",
        periode: "1870-1871",
        kata_kunci: "prancis, prusia, perang, unifikasi jerman",
        wilayah: "Perancis, Jerman, Alsace-Lorraine",
        tokoh_penting: ["Otto von Bismarck", "Wilhelm I", "Napoleon III", "MacMahon"],
        dampak: "Unifikasi Jerman, humiliasi Perancis, penyerahan Alsace-Lorraine, rasa dendam",
        penyebab: "Dislokasi diplomatik, ambisi Bismarck untuk unifikasi",
        akibat: "Jerman bersatu, Perancis lemah, fondasi Perang Dunia I",
        sumber_referensi: ["The Franco-Prussian War", "Bismarck's Wars"],
        kategori: "Perang"
      },
      {
        judul_sejarah: "Unifikasi Italia",
        deskripsi_sejarah: "Unifikasi Italia (1861-1870) adalah proses pemersatuan negara-negara Italia yang terpisah menjadi satu negara Italia modern. Dipimpin oleh tokoh-tokoh seperti Cavour, Garibaldi, dan Victor Emmanuel II, unifikasi ini mengubah peta Eropa.",
        periode: "1861-1870",
        kata_kunci: "italia, unifikasi, cavour, garibaldi",
        wilayah: "Italia, Eropa Selatan",
        tokoh_penting: ["Camillo Cavour", "Giuseppe Garibaldi", "Victor Emmanuel II"],
        dampak: "Pembentukan negara Italia modern, perubahan peta Eropa, kekuatan baru di Eropa",
        penyebab: "Nasionalisme Italia, dukungan Perancis, kelemahan Austria",
        akibat: "Italia bersatu, penting sebagai kekuatan Eropa, ekspansi imperium",
        sumber_referensi: ["The Italian Unification", "Garibaldi and Italian Independence"],
        kategori: "Unifikasi"
      },
      {
        judul_sejarah: "Perjanjian Westphalia",
        deskripsi_sejarah: "Perjanjian Westphalia (1648) adalah perjanjian damai yang mengakhiri Perang Tiga Puluh Tahun di Eropa. Perjanjian ini menetapkan sistem negara-bangsa modern dan prinsip kedaulatan nasional.",
        periode: "1648",
        kata_kunci: "westphalia, perjanjian, perang, tiga puluh tahun",
        wilayah: "Eropa",
        tokoh_penting: ["Cardinal Richelieu", "Olivares", "Oxenstierna"],
        dampak: "Sistem negara-bangsa modern, kedaulatan nasional, akhir Perang Tiga Puluh Tahun",
        penyebab: "Kelelahan perang, kebutuhan perdamaian di Eropa",
        akibat: "Fondasi hukum internasional modern, sistem Eropa yang seimbang",
        sumber_referensi: ["The Treaty of Westphalia", "Birth of the Modern State System"],
        kategori: "Perjanjian Historis"
      },
      {
        judul_sejarah: "Dinasti Ashoka (Kerajaan Maurya)",
        deskripsi_sejarah: "Dinasti Ashoka (268-232 SM) adalah dinasti besar di Kerajaan Maurya yang memerintah sebagian besar India. Ashoka terkenal dengan konversi ke Buddha dan penyebaran Buddhisme di seluruh Asia.",
        periode: "268-232 SM",
        kata_kunci: "ashoka, maurya, buddha, india",
        wilayah: "India, Asia Selatan",
        tokoh_penting: ["Emperor Ashoka", "Chandragupta Maurya"],
        dampak: "Penyebaran Buddhisme ke seluruh Asia, taman candi Buddha, edil Ashoka",
        penyebab: "Konversi pribadi Ashoka ke Buddha setelah perang",
        akibat: "Buddhisme menjadi agama besar di Asia, warisan budaya Buddha",
        sumber_referensi: ["Emperor Ashoka", "The Mauryan Empire"],
        kategori: "Dinasti"
      },
      {
        judul_sejarah: "Peradaban Dong Son",
        deskripsi_sejarah: "Peradaban Dong Son (1000 SM - 100 M) adalah peradaban kuno di Vietnam dan Asia Tenggara yang terkenal dengan drum perunggu dan keramik berkualitas tinggi.",
        periode: "1000 SM - 100 M",
        kata_kunci: "dong son, vietnam, drum, perunggu",
        wilayah: "Vietnam, Asia Tenggara",
        tokoh_penting: ["Penduduk Dong Son Pra-sejarah"],
        dampak: "Drum perunggu yang indah, kemampuan metalurgi, perdagangan maritim",
        penyebab: "Lokasi geografis strategis, kemampuan teknik metallurgi",
        akibat: "Pengaruh pada budaya Vietnam, warisan budaya bertahan",
        sumber_referensi: ["Dong Son Civilization", "Bronze Age Southeast Asia"],
        kategori: "Peradaban"
      },
      {
        judul_sejarah: "Kremlin Moskow",
        deskripsi_sejarah: "Kremlin Moskow menjadi pusat kekuasaan Rusia selama berabad-abad, melambangkan supremasi Rusia dan kemudian Soviet. Kremlin adalah simbol otoritas Rusia dalam sejarah dan saat ini.",
        periode: "1300-Sekarang",
        kata_kunci: "kremlin, moskow, rusia, pusat kekuasaan",
        wilayah: "Moskow, Rusia",
        tokoh_penting: ["Tsar Rusia", "Soviet Leaders", "Putin"],
        dampak: "Simbol otoritas Rusia, pusat pemerintahan, situs bersejarah",
        penyebab: "Pembangunan Kremlin sebagai benteng pertahanan",
        akibat: "Kremlin tetap pusat kekuasaan hingga kini, UNESCO World Heritage",
        sumber_referensi: ["The Kremlin", "History of Moscow Kremlin"],
        kategori: "Situs Bersejarah"
      },
      {
        judul_sejarah: "Perang Dunia Ketiga Kuba",
        deskripsi_sejarah: "Krisis Teluk Babi (1961) dan Krisis Misil Kuba (1962) adalah peristiwa paling berbahaya dalam Perang Dingin yang mendorong dunia menjelang perang nuklir.",
        periode: "1961-1962",
        kata_kunci: "kuba, krisis, misil, perang dingin",
        wilayah: "Kuba, Amerika",
        tokoh_penting: ["John F. Kennedy", "Nikita Khrushchev", "Fidel Castro"],
        dampak: "Mencegah Perang Dunia III, garis telepon merah dibentuk, percakapan Amerika-Soviet",
        penyebab: "Revolusi Kuba 1959, penempatan misil Soviet di Kuba",
        akibat: "De-eskalasi Perang Dingin, perjanjian non-proliferasi nuklir",
        sumber_referensi: ["The Cuban Missile Crisis", "13 Days: A Memoir"],
        kategori: "Perang Dingin"
      },
      {
        judul_sejarah: "Revolusi Perangkat Lunak (Era Digital Modern)",
        deskripsi_sejarah: "Revolusi perangkat lunak dimulai dari 1980an hingga sekarang, menciptakan Internet, cloud computing, AI, dan transformasi digital global.",
        periode: "1980-Sekarang",
        kata_kunci: "perangkat lunak, digital, komputer, internet, ai",
        wilayah: "Global",
        tokoh_penting: ["Bill Gates", "Steve Jobs", "Linus Torvalds", "Tim Berners-Lee"],
        dampak: "Internet global, smartphone, AI dan machine learning, transformasi semua industri",
        penyebab: "Perkembangan chip komputer, miniaturisasi, demand pasar global",
        akibat: "Era digital, media sosial, e-commerce, digital transformation",
        sumber_referensi: ["The Software Revolution", "Code: The Hidden Language of Computing"],
        kategori: "Era Modern"
      }
    ];
    
    // Hapus data lama (opsional)
    await Sejarah.deleteMany({});
    console.log('Data lama dihapus');
    
    // Tambahkan data baru
    await Sejarah.insertMany(dataSejarah);
    console.log(`${dataSejarah.length} topik sejarah berhasil ditambahkan ke database`);
    
    // Tutup koneksi
    await mongoose.connection.close();
    console.log('Koneksi database ditutup');
    
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}

// Jalankan fungsi
tambahDataSejarah();
