// seed-tokoh.js - Script untuk menambahkan data tokoh sejarah dunia ke database
const mongoose = require('mongoose');
const koneksiDatabase = require('./config/database');
const Tokoh = require('./models/tokoh');

async function tambahDataTokoh() {
  try {
    // Koneksi ke database
    await koneksiDatabase();
    
    // Data tokoh sejarah yang akan ditambahkan
    const dataTokoh = [
      {
        nama_tokoh: "Alexander Agung",
        deskripsi_tokoh: "Alexander Agung (356-323 SM) adalah raja Makedonia yang menciptakan salah satu imperium terbesar dalam sejarah. Dia menguasai wilayah dari Yunani hingga India dalam waktu singkat dengan strategi militer yang revolusioner.",
        periode_hidup: "356-323 SM",
        negara_asal: "Makedonia",
        bidang_keahlian: "Militer, Penaklukan, Strategi",
        kontribusi_utama: "Memperluas Helenisme ke Asia, menciptakan rute perdagangan internasional",
        pencapaian_penting: ["Menaklukkan Persia", "Mendirikan Alexandria", "Strategi taktis Gaugamela"],
        pengaruh_sejarah: "Mengubah peta dunia, menyebarkan budaya Yunani ke seluruh Asia",
        legacy: "Dianggap sebagai salah satu penakluk terbesar dalam sejarah",
        sumber_referensi: ["Life of Alexander", "Alexander the Great by Philip Freeman"],
        kategori: "Pemimpin Militer"
      },
      {
        nama_tokoh: "Julius Caesar",
        deskripsi_tokoh: "Julius Caesar (100-44 SM) adalah jenderal dan politisi Romawi yang memperluas kekuasaan Romawi ke Gaul dan Mesir. Dia juga menjadi diktator Romawi sebelum dibunuh di Senat.",
        periode_hidup: "100-44 SM",
        negara_asal: "Romawi",
        bidang_keahlian: "Militer, Politik, Strategi",
        kontribusi_utama: "Penaklukan Gaul, reformasi pemerintahan Romawi",
        pencapaian_penting: ["Penaklukan Gaul", "Kemenangan di Pharsakos", "Menjadi Diktator"],
        pengaruh_sejarah: "Mengubah struktur pemerintahan Romawi, memulai era Kekaisaran",
        legacy: "Salah satu tokoh paling berpengaruh dalam sejarah Romawi",
        sumber_referensi: ["Commentarii de Bello Gallico", "Caesar: Life of a Colossus"],
        kategori: "Pemimpin Militer"
      },
      {
        nama_tokoh: "Napoleon Bonaparte",
        deskripsi_tokoh: "Napoleon Bonaparte (1769-1821) adalah jenderal dan kaisar Perancis yang merevolusi taktik militer dan hukum modern. Dia menaklukkan sebagian besar Eropa sebelum dikalahkan.",
        periode_hidup: "1769-1821",
        negara_asal: "Perancis",
        bidang_keahlian: "Militer, Hukum, Administrasi",
        kontribusi_utama: "Kode Napoleon, reformasi hukum Eropa",
        pencapaian_penting: ["Kemenangan Austerlitz", "Penaklukan Mesir", "Kode Napoleon"],
        pengaruh_sejarah: "Mengubah sistem hukum modern, merevolusi taktik militer",
        legacy: "Salah satu pemimpin paling berpengaruh dalam sejarah Eropa",
        sumber_referensi: ["Napoleon by Andrew Roberts", "The Life of Napoleon"],
        kategori: "Pemimpin Militer"
      },
      {
        nama_tokoh: "Queen Victoria",
        deskripsi_tokoh: "Queen Victoria (1819-1901) adalah ratu Inggris yang memerintah selama 64 tahun. Era Victoriannya ditandai dengan ekspansi Kerajaan Inggris dan kemajuan industri.",
        periode_hidup: "1819-1901",
        negara_asal: "Inggris",
        bidang_keahlian: "Pemerintahan, Diplomasi",
        kontribusi_utama: "Ekspansi Kerajaan Inggris, kemajuan industri",
        pencapaian_penting: ["Memperluas Kerajaan Inggris", "Era Industri", "Menciptakan Era Victorian"],
        pengaruh_sejarah: "Mengubah Inggris menjadi kekuatan dunia terbesar pada masanya",
        legacy: "Era Victoria dianggap sebagai puncak kekuasaan Inggris",
        sumber_referensi: ["Queen Victoria by A.N. Wilson", "The Young Victoria"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Abraham Lincoln",
        deskripsi_tokoh: "Abraham Lincoln (1809-1865) adalah presiden Amerika Serikat ke-16 yang memimpin negara melalui Perang Sipil. Dia menghapuskan perbudakan dan memperkuat persatuan Amerika.",
        periode_hidup: "1809-1865",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Pemerintahan, Politik",
        kontribusi_utama: "Penghapusan perbudakan, memperkuat persatuan Amerika",
        pencapaian_penting: ["Emancipation Proclamation", "Kemenangan Perang Sipil", "Persatuan Amerika"],
        pengaruh_sejarah: "Menghapuskan perbudakan di Amerika, memperkuat demokrasi",
        legacy: "Dianggap sebagai presiden terbaik Amerika",
        sumber_referensi: ["Life of Lincoln", "Team of Rivals"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Mahatma Gandhi",
        deskripsi_tokoh: "Mahatma Gandhi (1869-1948) adalah pemimpin India yang memimpin gerakan kemerdekaan melalui non-kekerasan. Dia menginspirasi gerakan sipil di seluruh dunia dengan filosofi Satyagraha.",
        periode_hidup: "1869-1948",
        negara_asal: "India",
        bidang_keahlian: "Gerakan Kemerdekaan, Filosofi",
        kontribusi_utama: "Kemerdekaan India, gerakan non-kekerasan",
        pencapaian_penting: ["Kemerdekaan India", "Salt March", "Filosofi Non-kekerasan"],
        pengaruh_sejarah: "Menginspirasi gerakan kemerdekaan di seluruh dunia",
        legacy: "Bapak kemerdekaan India, simbol gerakan non-kekerasan",
        sumber_referensi: ["My Experiments with Truth", "The Life of Mahatma Gandhi"],
        kategori: "Pemimpin Gerakan"
      },
      {
        nama_tokoh: "Winston Churchill",
        deskripsi_tokoh: "Winston Churchill (1874-1965) adalah Perdana Menteri Inggris yang memimpin negara melalui Perang Dunia II. Dia dikenal dengan retorika yang kuat dan kepemimpinan yang inspiratif.",
        periode_hidup: "1874-1965",
        negara_asal: "Inggris",
        bidang_keahlian: "Pemerintahan, Militer, Retorika",
        kontribusi_utama: "Kepemimpinan selama Perang Dunia II",
        pencapaian_penting: ["Kemenangan di Perang Dunia II", "Retorika inspiratif", "Persatuan Barat"],
        pengaruh_sejarah: "Memimpin Inggris pada waktu kritis Perang Dunia II",
        legacy: "Salah satu pemimpin paling dihormati di Abad 20",
        sumber_referensi: ["The Second World War", "Churchill by Andrew Roberts"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Albert Einstein",
        deskripsi_tokoh: "Albert Einstein (1879-1955) adalah fisikawan teoritis yang mengembangkan teori relativitas. Penemuannya merevolusi pemahaman manusia tentang ruang, waktu, dan gravitasi.",
        periode_hidup: "1879-1955",
        negara_asal: "Jerman/Amerika",
        bidang_keahlian: "Fisika, Sains",
        kontribusi_utama: "Teori Relativitas, E=mc²",
        pencapaian_penting: ["Teori Relativitas Umum", "Teori Relativitas Khusus", "Prediksi Lubang Hitam"],
        pengaruh_sejarah: "Merevolusi fisika modern dan pemahaman alam semesta",
        legacy: "Dianggap sebagai fisikawan terbesar dalam sejarah",
        sumber_referensi: ["Relativity: The Special and General Theory", "Einstein by Walter Isaacson"],
        kategori: "Ilmuwan"
      },
      {
        nama_tokoh: "Marie Curie",
        deskripsi_tokoh: "Marie Curie (1867-1934) adalah ilmuwan Polandia yang memenangkan dua Hadiah Nobel untuk penemuan dalam radioaktivitas. Dia adalah perempuan pertama yang memenangkan Nobel dan meninggal akibat paparan radiasi.",
        periode_hidup: "1867-1934",
        negara_asal: "Polandia/Perancis",
        bidang_keahlian: "Fisika, Kimia",
        kontribusi_utama: "Penemuan Radium dan Polonium, penelitian radioaktivitas",
        pencapaian_penting: ["Penemuan Radium", "Dua Hadiah Nobel", "Penelitian Radioaktivitas"],
        pengaruh_sejarah: "Membuka bidang baru dalam fisika dan kimia modern",
        legacy: "Perempuan pertama pemenang Nobel, pahlawan sains",
        sumber_referensi: ["Marie Curie: A Life", "Radioactive by Lauren Redniss"],
        kategori: "Ilmuwan"
      },
      {
        nama_tokoh: "Leonardo da Vinci",
        deskripsi_tokoh: "Leonardo da Vinci (1452-1519) adalah seniman dan ilmuwan Italia Renaissance yang jenius. Dia adalah polymath yang berkontribusi pada seni, sains, teknik, dan arsitektur.",
        periode_hidup: "1452-1519",
        negara_asal: "Italia",
        bidang_keahlian: "Seni, Sains, Teknik, Arsitektur",
        kontribusi_utama: "Karya seni ikonik, studi anatomi, desain mekanik",
        pencapaian_penting: ["Mona Lisa", "The Last Supper", "Sketsa Helikopter"],
        pengaruh_sejarah: "Merepresentasikan ideale Renaissance tentang pengetahuan universal",
        legacy: "Salah satu tokoh paling jenius dalam sejarah manusia",
        sumber_referensi: ["Leonardo da Vinci by Walter Isaacson", "The Notebooks of Leonardo da Vinci"],
        kategori: "Seniman dan Ilmuwan"
      },
      {
        nama_tokoh: "Michelangelo Buonarroti",
        deskripsi_tokoh: "Michelangelo (1475-1564) adalah seniman Italia Renaissance terbesar yang dikenal dengan patung David dan lukisan Kapel Sistina. Dia adalah master dalam seni patung, lukisan, dan arsitektur.",
        periode_hidup: "1475-1564",
        negara_asal: "Italia",
        bidang_keahlian: "Seni, Patung, Lukisan, Arsitektur",
        kontribusi_utama: "Karya seni Renaissance ikonik",
        pencapaian_penting: ["Patung David", "Kapel Sistina", "Basilica Santo Petrus"],
        pengaruh_sejarah: "Mendefinisikan standar keindahan dan teknik dalam seni Barat",
        legacy: "Master seni Renaissance yang dihormati sepanjang masa",
        sumber_referensi: ["Michelangelo by Christopher Hibbert", "The Complete Michelangelo"],
        kategori: "Seniman"
      },
      {
        nama_tokoh: "William Shakespeare",
        deskripsi_tokoh: "William Shakespeare (1564-1616) adalah penulis dan dramawan Inggris yang dianggap sebagai penulis terbesar dalam bahasa Inggris. Karya-karyanya terus dimainkan di seluruh dunia.",
        periode_hidup: "1564-1616",
        negara_asal: "Inggris",
        bidang_keahlian: "Sastra, Drama",
        kontribusi_utama: "Karya-karya drama dan puisi yang abadi",
        pencapaian_penting: ["Hamlet", "Romeo dan Juliet", "Macbeth"],
        pengaruh_sejarah: "Mendefinisikan bentuk drama modern dan bahasa Inggris",
        legacy: "Penulis terbesar dalam sejarah sastra Inggris",
        sumber_referensi: ["The Complete Works of Shakespeare", "Shakespeare by Bill Bryson"],
        kategori: "Penulis"
      },
      {
        nama_tokoh: "Ludwig van Beethoven",
        deskripsi_tokoh: "Ludwig van Beethoven (1770-1827) adalah komposer Jerman yang merevolusi musik klasik. Dia menciptakan simfoni-simfoni masterpiece meskipun mengalami ketulian.",
        periode_hidup: "1770-1827",
        negara_asal: "Jerman",
        bidang_keahlian: "Musik, Komposisi",
        kontribusi_utama: "Simfoni revolusioner, musik instrumental modern",
        pencapaian_penting: ["Simfoni ke-9", "Sonata Cahaya Bulan", "Simfoni Heroik"],
        pengaruh_sejarah: "Mentransisi musik dari Klasik ke Romantik",
        legacy: "Salah satu komposer terbesar dalam sejarah musik",
        sumber_referensi: ["Beethoven by Jan Swafford", "The Life and Work of Beethoven"],
        kategori: "Musisi"
      },
      {
        nama_tokoh: "Wolfgang Amadeus Mozart",
        deskripsi_tokoh: "Wolfgang Amadeus Mozart (1756-1791) adalah komposer Austria yang luar biasa berbakat sejak kecil. Dia menciptakan lebih dari 600 komposisi musik yang terkenal di seluruh dunia.",
        periode_hidup: "1756-1791",
        negara_asal: "Austria",
        bidang_keahlian: "Musik, Komposisi",
        kontribusi_utama: "Komposisi musik klasik yang sempurna",
        pencapaian_penting: ["Requiem", "Don Giovanni", "Magic Flute"],
        pengaruh_sejarah: "Mendefinisikan standar musik klasik modern",
        legacy: "Komposer paling produktif dan berbakat dalam sejarah musik",
        sumber_referensi: ["Mozart by Andrew Steptoe", "Mozart: The Genius and The Man"],
        kategori: "Musisi"
      },
      {
        nama_tokoh: "Charles Darwin",
        deskripsi_tokoh: "Charles Darwin (1809-1882) adalah naturalis Inggris yang mengembangkan teori evolusi. Karyanya 'On the Origin of Species' merevolusi pemahaman biologi dan kehidupan.",
        periode_hidup: "1809-1882",
        negara_asal: "Inggris",
        bidang_keahlian: "Biologi, Naturalis",
        kontribusi_utama: "Teori Evolusi, seleksi alam",
        pencapaian_penting: ["On the Origin of Species", "Voyage of the Beagle", "Seleksi Alam"],
        pengaruh_sejarah: "Merevolusi pemahaman tentang kehidupan dan evolusi",
        legacy: "Bapak teori evolusi modern",
        sumber_referensi: ["On the Origin of Species", "Darwin by Adrian Desmond"],
        kategori: "Ilmuwan"
      },
      {
        nama_tokoh: "Isaac Newton",
        deskripsi_tokoh: "Isaac Newton (1643-1727) adalah fisikawan dan matematikawan Inggris yang merumuskan hukum gravitasi dan gerak. Dia merevolusi pemahaman fisika dan sains modern.",
        periode_hidup: "1643-1727",
        negara_asal: "Inggris",
        bidang_keahlian: "Fisika, Matematika",
        kontribusi_utama: "Hukum Gravitasi, Kalkulus, Optika",
        pencapaian_penting: ["Principia Mathematica", "Hukum Gravitasi", "Teleskop Refleksi"],
        pengaruh_sejarah: "Mendirikan fondasi fisika klasik modern",
        legacy: "Salah satu ilmuwan terbesar sepanjang masa",
        sumber_referensi: ["Isaac Newton by James Gleick", "Principia Mathematica"],
        kategori: "Ilmuwan"
      },
      {
        nama_tokoh: "Galileo Galilei",
        deskripsi_tokoh: "Galileo Galilei (1564-1642) adalah astronom dan fisikawan Italia yang memajukan metode ilmiah. Dia menggunakan teleskop untuk mengamati langit dan mendukung heliosentrisme.",
        periode_hidup: "1564-1642",
        negara_asal: "Italia",
        bidang_keahlian: "Astronomi, Fisika",
        kontribusi_utama: "Metode ilmiah modern, observasi teleskop",
        pencapaian_penting: ["Observasi Bulan dan Jupiter", "Heliosentrisme", "Teleskop"],
        pengaruh_sejarah: "Memulai revolusi sains modern",
        legacy: "Bapak metode ilmiah modern",
        sumber_referensi: ["Galileo by Andrew Gregory", "The Affair of the Sunspots"],
        kategori: "Ilmuwan"
      },
      {
        nama_tokoh: "Socrates",
        deskripsi_tokoh: "Socrates (470-399 SM) adalah filsuf Yunani yang bertanya-tanya tentang kehidupan dan moral. Meskipun tidak menulis, pengaruhnya melalui murid-muridnya sangat besar dalam filsafat Barat.",
        periode_hidup: "470-399 SM",
        negara_asal: "Yunani",
        bidang_keahlian: "Filosofi, Etika",
        kontribusi_utama: "Metode Socratic, filosofi moral",
        pencapaian_penting: ["Metode Socratic", "Penyelidikan Etika", "Pengaruh pada Plato"],
        pengaruh_sejarah: "Pendiri tradisi filosofi Barat",
        legacy: "Bapak filosofi Barat",
        sumber_referensi: ["Apology by Plato", "The Life of Socrates"],
        kategori: "Filsuf"
      },
      {
        nama_tokoh: "Plato",
        deskripsi_tokoh: "Plato (428-348 SM) adalah filsuf Yunani yang mendirikan Akademi dan mengembangkan teori bentuk. Karya-karyanya membentuk fondasi filosofi Barat.",
        periode_hidup: "428-348 SM",
        negara_asal: "Yunani",
        bidang_keahlian: "Filosofi, Metafisika",
        kontribusi_utama: "Teori Bentuk, Akademi Filsafat",
        pencapaian_penting: ["Republic", "Phaedo", "Timaeus"],
        pengaruh_sejarah: "Membentuk tradisi filosofi Barat",
        legacy: "Salah satu filsuf terbesar dalam sejarah",
        sumber_referensi: ["The Republic", "Plato by A.E. Taylor"],
        kategori: "Filsuf"
      },
      {
        nama_tokoh: "Aristoteles",
        deskripsi_tokoh: "Aristoteles (384-322 SM) adalah filsuf Yunani yang mengembangkan logika dan metafisika. Dia juga berkontribusi pada ilmu alam, etika, dan politik.",
        periode_hidup: "384-322 SM",
        negara_asal: "Yunani",
        bidang_keahlian: "Filosofi, Logika, Sains",
        kontribusi_utama: "Logika formal, metafisika, klasifikasi ilmu",
        pencapaian_penting: ["Logika Formal", "Metafisika", "Etika Nicomachean"],
        pengaruh_sejarah: "Membentuk filsafat dan sains abad pertengahan",
        legacy: "Filsuf paling berpengaruh dalam sejarah intelektual",
        sumber_referensi: ["Metaphysics", "Aristotle by Jonathan Barnes"],
        kategori: "Filsuf"
      },
      {
        nama_tokoh: "Immanuel Kant",
        deskripsi_tokoh: "Immanuel Kant (1724-1804) adalah filsuf Jerman yang mengembangkan filosofi kritis. Karya-karyanya merevolusi epistemologi dan etika modern.",
        periode_hidup: "1724-1804",
        negara_asal: "Jerman",
        bidang_keahlian: "Filosofi, Epistemologi, Etika",
        kontribusi_utama: "Filosofi Kritis, Imperatif Kategoris",
        pencapaian_penting: ["Critique of Pure Reason", "Critique of Practical Reason", "Imperatif Kategoris"],
        pengaruh_sejarah: "Merevolusi epistemologi dan etika filsafat",
        legacy: "Filsuf paling berpengaruh di era modern",
        sumber_referensi: ["Critique of Pure Reason", "Kant by Sebastian Gardner"],
        kategori: "Filsuf"
      },
      {
        nama_tokoh: "René Descartes",
        deskripsi_tokoh: "René Descartes (1596-1650) adalah filsuf Perancis yang mengembangkan metode ilmiah modern dengan 'Cogito ergo sum'. Dia juga berkontribusi pada matematika dan geometri analitik.",
        periode_hidup: "1596-1650",
        negara_asal: "Perancis",
        bidang_keahlian: "Filosofi, Matematika, Sains",
        kontribusi_utama: "Metode Ilmiah, Dualism Cartesian, Geometri Analitik",
        pencapaian_penting: ["Discourse on Method", "Cogito ergo sum", "Geometri Analitik"],
        pengaruh_sejarah: "Mendirikan fondasi filosofi modern",
        legacy: "Bapak filosofi modern",
        sumber_referensi: ["Discourse on Method", "Descartes by Jonathan Ree"],
        kategori: "Filsuf"
      },
      {
        nama_tokoh: "Friedrich Nietzsche",
        deskripsi_tokoh: "Friedrich Nietzsche (1844-1900) adalah filsuf Jerman yang mengkritik moralitas tradisional. Konsep 'Übermensch' dan 'Will to Power' sangat berpengaruh pada filosofi modern.",
        periode_hidup: "1844-1900",
        negara_asal: "Jerman",
        bidang_keahlian: "Filosofi, Metafisika",
        kontribusi_utama: "Kritik Moralitas, Übermensch, Will to Power",
        pencapaian_penting: ["Beyond Good and Evil", "Thus Spoke Zarathustra", "The Will to Power"],
        pengaruh_sejarah: "Mempengaruhi filosofi, seni, dan budaya abad 20",
        legacy: "Filsuf paling kontroversial dan berpengaruh di era modern",
        sumber_referensi: ["Thus Spoke Zarathustra", "Nietzsche by Peter Kreeft"],
        kategori: "Filsuf"
      },
      {
        nama_tokoh: "Karl Marx",
        deskripsi_tokoh: "Karl Marx (1818-1883) adalah filsuf dan ekonom Jerman yang mengembangkan Marxisme. Teorinya tentang kapitalisme dan komunisme sangat mempengaruhi gerakan sosial abad 20.",
        periode_hidup: "1818-1883",
        negara_asal: "Jerman",
        bidang_keahlian: "Filosofi, Ekonomi, Sosiologi",
        kontribusi_utama: "Teori Marxisme, Analisis Kapitalisme",
        pencapaian_penting: ["The Communist Manifesto", "Das Kapital", "Historical Materialism"],
        pengaruh_sejarah: "Mempengaruhi revolusi sosial abad 20",
        legacy: "Pemikir paling berpengaruh dalam sosiologi modern",
        sumber_referensi: ["Das Kapital", "The Communist Manifesto"],
        kategori: "Filsuf dan Ekonom"
      },
      {
        nama_tokoh: "John Locke",
        deskripsi_tokoh: "John Locke (1632-1704) adalah filsuf Inggris yang mengembangkan teori liberal dan hak asasi manusia. Idenya tentang 'life, liberty, and property' mempengaruhi Revolusi Amerika.",
        periode_hidup: "1632-1704",
        negara_asal: "Inggris",
        bidang_keahlian: "Filosofi Politik, Epistemologi",
        kontribusi_utama: "Teori Hak Asasi, Liberalisme",
        pencapaian_penting: ["Two Treatises of Government", "Essay Concerning Human Understanding", "Hak Asasi"],
        pengaruh_sejarah: "Mempengaruhi Revolusi Amerika dan Perancis",
        legacy: "Bapak liberalisme dan hak asasi manusia",
        sumber_referensi: ["Two Treatises of Government", "John Locke by E.J. Lowe"],
        kategori: "Filsuf Politik"
      },
      {
        nama_tokoh: "Thomas Jefferson",
        deskripsi_tokoh: "Thomas Jefferson (1743-1826) adalah presiden Amerika ke-3 yang menulis Deklarasi Kemerdekaan Amerika. Dia juga filsuf dan advokat kebebasan dan demokrasi.",
        periode_hidup: "1743-1826",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Politik, Filosofi",
        kontribusi_utama: "Deklarasi Kemerdekaan, Presidensi Amerika",
        pencapaian_penting: ["Deklarasi Kemerdekaan", "Pembelian Louisiana", "Ekspansi Amerika"],
        pengaruh_sejarah: "Mendirikan prinsip-prinsip demokrasi Amerika",
        legacy: "Bapak pendiri Amerika",
        sumber_referensi: ["The Declaration of Independence", "Jefferson by Jon Meacham"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "George Washington",
        deskripsi_tokoh: "George Washington (1732-1799) adalah panglima militer dan presiden pertama Amerika yang memimpin perjuangan kemerdekaan. Dia dianggap sebagai 'Bapak Bangsa' Amerika.",
        periode_hidup: "1732-1799",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Militer, Politik",
        kontribusi_utama: "Kepemimpinan Perang Kemerdekaan, Presiden Pertama",
        pencapaian_penting: ["Kemenangan Perang Kemerdekaan", "Presiden Pertama", "Menetapkan Tradisi"],
        pengaruh_sejarah: "Memimpin pembentukan Amerika Serikat",
        legacy: "Bapak Bangsa Amerika",
        sumber_referensi: ["Founding Father", "Washington by Ron Chernow"],
        kategori: "Pemimpin Militer"
      },
      {
        nama_tokoh: "Martin Luther King Jr.",
        deskripsi_tokoh: "Martin Luther King Jr. (1929-1968) adalah pemimpin gerakan hak-hak sipil Amerika yang memperjuangkan kesetaraan ras melalui non-kekerasan. Pidatonya 'I Have a Dream' menginspirasi jutaan orang.",
        periode_hidup: "1929-1968",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Gerakan Sipil, Retorika",
        kontribusi_utama: "Gerakan Hak Asasi Sipil, Non-kekerasan",
        pencapaian_penting: ["I Have a Dream Speech", "Civil Rights Act", "Nobel Peace Prize"],
        pengaruh_sejarah: "Memimpin gerakan kesetaraan ras di Amerika",
        legacy: "Simbol perjuangan hak asasi sipil",
        sumber_referensi: ["I Have a Dream", "The Life and Legacy of MLK Jr."],
        kategori: "Pemimpin Gerakan"
      },
      {
        nama_tokoh: "Nelson Mandela",
        deskripsi_tokoh: "Nelson Mandela (1918-2013) adalah pemimpin anti-apartheid Afrika Selatan yang dipenjarakan 27 tahun. Dia menjadi presiden pertama Afrika Selatan pasca-apartheid dan mempromosikan rekonsiliasi.",
        periode_hidup: "1918-2013",
        negara_asal: "Afrika Selatan",
        bidang_keahlian: "Gerakan Anti-apartheid, Pemerintahan",
        kontribusi_utama: "Penghapusan apartheid, Rekonsiliasi Nasional",
        pencapaian_penting: ["Pembebasan dari Penjara", "Presiden Afrika Selatan", "Truth and Reconciliation"],
        pengaruh_sejarah: "Mengakhiri apartheid di Afrika Selatan",
        legacy: "Simbol perlawanan dan perdamaian",
        sumber_referensi: ["Long Walk to Freedom", "The Life of Nelson Mandela"],
        kategori: "Pemimpin Gerakan"
      },
      {
        nama_tokoh: "Mother Teresa",
        deskripsi_tokoh: "Mother Teresa (1910-1997) adalah nun Albanesia yang mendedikasikan hidupnya untuk membantu orang miskin dan sakit di Kalkuta, India. Dia memenangkan Nobel Peace Prize untuk karyanya.",
        periode_hidup: "1910-1997",
        negara_asal: "Albania",
        bidang_keahlian: "Kemanusiaan, Sosial",
        kontribusi_utama: "Pelayanan kepada orang miskin dan sakit",
        pencapaian_penting: ["Missionaries of Charity", "Nobel Peace Prize", "Pelayanan di Kalkuta"],
        pengaruh_sejarah: "Menginspirasi gerakan kemanusiaan global",
        legacy: "Simbol kepedulian dan kasih sayang",
        sumber_referensi: ["No Greater Love", "The Life of Mother Teresa"],
        kategori: "Tokoh Kemanusiaan"
      },
      {
        nama_tokoh: "Confucius",
        deskripsi_tokoh: "Confucius (551-479 SM) adalah filsuf Cina yang mengembangkan sistem etika dan moral. Ajarannya tentang keluarga, loyalitas, dan keadilan mempengaruhi peradaban Asia selama berabad-abad.",
        periode_hidup: "551-479 SM",
        negara_asal: "Cina",
        bidang_keahlian: "Filosofi, Etika",
        kontribusi_utama: "Konfusianisme, Etika Sosial",
        pencapaian_penting: ["Analects", "Etika Sosial", "Pengaruh Peradaban Asia"],
        pengaruh_sejarah: "Membentuk peradaban Asia Timur",
        legacy: "Filsuf paling berpengaruh di Asia",
        sumber_referensi: ["Analects of Confucius", "Confucius by Jonathan D. Spence"],
        kategori: "Filsuf"
      },
      {
        nama_tokoh: "Laozi",
        deskripsi_tokoh: "Laozi (fl. 6 abad SM) adalah filsuf Cina kuno yang dianggap sebagai pendiri Taoisme. Karya filosofisnya 'Tao Te Ching' merupakan salah satu teks filosofis terpenting di dunia.",
        periode_hidup: "6 abad SM",
        negara_asal: "Cina",
        bidang_keahlian: "Filosofi, Spiritualitas",
        kontribusi_utama: "Taoisme, Tao Te Ching",
        pencapaian_penting: ["Tao Te Ching", "Filosofi Tao", "Spiritualitas Timur"],
        pengaruh_sejarah: "Membentuk spiritualitas dan filosofi Asia",
        legacy: "Pendiri Taoisme dan pengaruh filosofi Timur",
        sumber_referensi: ["Tao Te Ching", "Laozi and the Tao Te Ching"],
        kategori: "Filsuf"
      },
      {
        nama_tokoh: "Buddha (Siddhartha Gautama)",
        deskripsi_tokoh: "Buddha (563-483 SM) adalah pencerahan spiritual yang mengembangkan Buddhisme. Ajarannya tentang penderitaan dan pencerahan mempengaruhi miliaran orang di seluruh dunia.",
        periode_hidup: "563-483 SM",
        negara_asal: "India",
        bidang_keahlian: "Spiritualitas, Filosofi",
        kontribusi_utama: "Buddhisme, Dharma",
        pencapaian_penting: ["Pencerahan", "Ajarannya empat mulia sejati", "Buddhisme"],
        pengaruh_sejarah: "Mempengaruhi miliaran pengikut di seluruh dunia",
        legacy: "Pendiri Buddhisme",
        sumber_referensi: ["The Life of Buddha", "Buddhist Scriptures"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Jesus Christ",
        deskripsi_tokoh: "Jesus Christ (4 SM - 30 M) adalah tokoh agama Yahudi yang menjadi fondasi Agama Kristen. Ajarannya tentang cinta dan kasih sayang mempengaruhi peradaban Barat selama dua milenium.",
        periode_hidup: "4 SM - 30 M",
        negara_asal: "Palestina",
        bidang_keahlian: "Spiritualitas, Agama",
        kontribusi_utama: "Agama Kristen, Ajarankasih sayang",
        pencapaian_penting: ["Agama Kristen", "Injil", "Pengaruh Peradaban Barat"],
        pengaruh_sejarah: "Mempengaruhi miliaran pengikut dan peradaban Barat",
        legacy: "Pendiri Agama Kristen",
        sumber_referensi: ["The New Testament", "The Life of Jesus"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Muhammad",
        deskripsi_tokoh: "Muhammad (570-632 M) adalah nabi Islam yang mengembangkan Agama Islam. Ajarannya melalui Alquran mempengaruhi miliaran pengikut dan membentuk peradaban Islam.",
        periode_hidup: "570-632 M",
        negara_asal: "Arab Saudi",
        bidang_keahlian: "Spiritualitas, Agama",
        kontribusi_utama: "Agama Islam, Alquran",
        pencapaian_penting: ["Agama Islam", "Alquran", "Pengaruh Peradaban Timur Tengah"],
        pengaruh_sejarah: "Mempengaruhi miliaran pengikut dan peradaban Islam",
        legacy: "Pendiri Agama Islam",
        sumber_referensi: ["The Quran", "The Life of Muhammad"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Cleopatra VII",
        deskripsi_tokoh: "Cleopatra VII (69-30 SM) adalah ratu Mesir terakhir yang terkenal dengan kecantikan dan kecerdasan politiknya. Dia berusaha mempertahankan kemerdekaan Mesir melawan kekuatan Romawi.",
        periode_hidup: "69-30 SM",
        negara_asal: "Mesir",
        bidang_keahlian: "Pemerintahan, Diplomasi",
        kontribusi_utama: "Kepemimpinan Mesir, Diplomasi",
        pencapaian_penting: ["Hubungan dengan Julius Caesar", "Aliansi dengan Antonius", "Mempertahankan Kemerdekaan Mesir"],
        pengaruh_sejarah: "Mempertahankan Mesir sebagai kekuatan independen",
        legacy: "Ratu legendaris Mesir kuno",
        sumber_referensi: ["Cleopatra by Stacy Schiff", "The Life of Cleopatra VII"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Joan of Arc",
        deskripsi_tokoh: "Joan of Arc (1412-1431) adalah pahlawan militer Perancis muda yang memimpin pasukan melawan Inggris dalam Perang Seratus Tahun. Dia dibakar sebagai penyihir namun menjadi simbol keberanian.",
        periode_hidup: "1412-1431",
        negara_asal: "Perancis",
        bidang_keahlian: "Militer, Perlawanan",
        kontribusi_utama: "Kepemimpinan militer, perlawanan Perancis",
        pencapaian_penting: ["Kemenangan Orlean", "Penobatan Raja Charles", "Martir Perancis"],
        pengaruh_sejarah: "Menginspirasi nasionalisme Perancis",
        legacy: "Pahlawan dan martir nasional Perancis",
        sumber_referensi: ["The Trial of Joan of Arc", "Joan of Arc by Mark Twain"],
        kategori: "Pahlawan Nasional"
      },
      {
        nama_tokoh: "Genghis Khan",
        deskripsi_tokoh: "Genghis Khan (1162-1227) adalah pemimpin Mongol yang menciptakan Kekaisaran Mongol terbesar dalam sejarah. Penaklukan-penaklukan militerlnya mengubah peta Asia dan perdagangan global.",
        periode_hidup: "1162-1227",
        negara_asal: "Mongolia",
        bidang_keahlian: "Militer, Pemerintahan",
        kontribusi_utama: "Kekaisaran Mongol, Jalur Sutra",
        pencapaian_penting: ["Kekaisaran Mongol Terbesar", "Penaklukan Asia", "Jalur Sutra"],
        pengaruh_sejarah: "Menciptakan imperium terbesar dalam sejarah",
        legacy: "Penakluk dan pemimpin paling terkenal",
        sumber_referensi: ["Genghis Khan by John Man", "The Mongol Empire"],
        kategori: "Pemimpin Militer"
      },
      {
        nama_tokoh: "Mansa Musa",
        deskripsi_tokoh: "Mansa Musa (1280-1337) adalah raja Mali yang memerintah salah satu kerajaan teraya di Afrika abad pertengahan. Kekayaannya yang luar biasa membuat Mali menjadi pusat perdagangan emas.",
        periode_hidup: "1280-1337",
        negara_asal: "Mali (Afrika)",
        bidang_keahlian: "Pemerintahan, Perdagangan",
        kontribusi_utama: "Kekayaan Mali, Pusat Pendidikan Islam",
        pencapaian_penting: ["Perjalanan Haji", "Kota Timbuktu", "Kekayaan Mali"],
        pengaruh_sejarah: "Membuat Mali pusat perdagangan emas Afrika",
        legacy: "Raja paling kaya dalam sejarah",
        sumber_referensi: ["Mansa Musa by Rudolph Ware", "The Mali Empire"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Zheng He",
        deskripsi_tokoh: "Zheng He (1371-1433) adalah penjelajah maritim Cina yang memimpin ekspedisi laut besar. Dia menjelajahi Asia, Afrika, dan Timur Tengah dengan armada kapal-kapal raksasa.",
        periode_hidup: "1371-1433",
        negara_asal: "Cina",
        bidang_keahlian: "Eksplorasi, Maritim",
        kontribusi_utama: "Ekspedisi Maritim Besar, Perdagangan Global",
        pencapaian_penting: ["Tujuh Ekspedisi Besar", "Penjelajahan Samudra Hindia", "Pertukaran Budaya"],
        pengaruh_sejarah: "Membuka rute perdagangan maritim global",
        legacy: "Penjelajah maritim terbesar era klasik",
        sumber_referensi: ["Zheng He by Edward L. Dreyer", "The Voyages of Zheng He"],
        kategori: "Penjelajah"
      },
      {
        nama_tokoh: "Christopher Columbus",
        deskripsi_tokoh: "Christopher Columbus (1451-1506) adalah penjelajah Italia yang berlayar untuk kerajaan Spanyol. Pelayarannya ke dunia Baru pada 1492 menandai era penjelajahan Eropa di Amerika.",
        periode_hidup: "1451-1506",
        negara_asal: "Italia/Spanyol",
        bidang_keahlian: "Eksplorasi, Maritim",
        kontribusi_utama: "Penjelajahan Amerika, Perdagangan Atlantik",
        pencapaian_penting: ["Perjalanan ke Dunia Baru 1492", "Penemuan Rute Baru", "Kontak Eropa-Amerika"],
        pengaruh_sejarah: "Memulai era eksplorasi Eropa di Amerika",
        legacy: "Penjelajah yang mengubah sejarah",
        sumber_referensi: ["The Life and Voyages of Columbus", "Columbus by Filson Young"],
        kategori: "Penjelajah"
      },
      {
        nama_tokoh: "Marco Polo",
        deskripsi_tokoh: "Marco Polo (1254-1324) adalah penjelajah Venetian yang melakukan perjalanan panjang ke Asia. Perjalanannya membuka Jalur Sutra dan memperkuat hubungan perdagangan Timur-Barat.",
        periode_hidup: "1254-1324",
        negara_asal: "Italia",
        bidang_keahlian: "Eksplorasi, Perdagangan",
        kontribusi_utama: "Perjalanan ke Asia, Jalur Sutra",
        pencapaian_penting: ["Perjalanan ke Cathay (Cina)", "Layanan Kublai Khan", "Jalur Sutra"],
        pengaruh_sejarah: "Membuka perdagangan antara Timur dan Barat",
        legacy: "Penjelajah paling terkenal era Abad Pertengahan",
        sumber_referensi: ["The Travels of Marco Polo", "Marco Polo by Manuel Komroff"],
        kategori: "Penjelajah"
      },
      {
        nama_tokoh: "Akbar Agung",
        deskripsi_tokoh: "Akbar Agung (1542-1605) adalah kaisar Mughal yang memperluas kekaisaran dan menciptakan kebijakan toleransi beragama. Dia dianggap sebagai kaisar Mughal terbesar.",
        periode_hidup: "1542-1605",
        negara_asal: "Mughal (India)",
        bidang_keahlian: "Pemerintahan, Militer, Administrasi",
        kontribusi_utama: "Ekspansi Kekaisaran Mughal, Toleransi Beragama",
        pencapaian_penting: ["Perluasan Kekaisaran Mughal", "Din-i-Ilahi (agama universal)", "Administrasi Tercanggih"],
        pengaruh_sejarah: "Membuat Kekaisaran Mughal mencapai puncak kekuasaannya",
        legacy: "Kaisar Mughal terbesar",
        sumber_referensi: ["Akbar the Great Mogul", "The Life of Akbar"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Suleiman Agung",
        deskripsi_tokoh: "Suleiman Agung (1494-1566) adalah sultan Ottoman yang memperluas kekaisaran Ottoman mencapai puncaknya. Dia dikenal sebagai legislator dan panglima perang yang hebat.",
        periode_hidup: "1494-1566",
        negara_asal: "Ottoman (Turki)",
        bidang_keahlian: "Pemerintahan, Militer",
        kontribusi_utama: "Perluasan Kekaisaran Ottoman, Hukum Ottoman",
        pencapaian_penting: ["Perluasan Kekaisaran Ottoman", "Legislasi Ottoman", "Kemenangan Militer"],
        pengaruh_sejarah: "Membuat Ottoman menjadi kekuatan Dunia",
        legacy: "Sultan Ottoman terbesar",
        sumber_referensi: ["Suleiman the Magnificent", "The Ottoman Empire"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Ivan the Terrible",
        deskripsi_tokoh: "Ivan IV (1530-1584) adalah tsar pertama Rusia yang memperluas kerajaan Rusia. Namun pemerintahannya juga ditandai dengan teror dan kekejaman yang ekstrem.",
        periode_hidup: "1530-1584",
        negara_asal: "Rusia",
        bidang_keahlian: "Pemerintahan, Militer",
        kontribusi_utama: "Ekspansi Rusia, Modernisasi Rusia",
        pencapaian_penting: ["Tsar Pertama Rusia", "Perluasan ke Kazan dan Astrakhan", "Reformasi Rusia"],
        pengaruh_sejarah: "Membentuk Rusia modern sebagai negara terpusat",
        legacy: "Tsar pertama Rusia",
        sumber_referensi: ["Ivan the Terrible", "The Life of Ivan IV"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Catherine the Great",
        deskripsi_tokoh: "Catherine II (1729-1796) adalah permaisuri Rusia yang memerintah selama 34 tahun. Dia memperluas Rusia menjadi negara besar dan membawa pencerahan ke Rusia.",
        periode_hidup: "1729-1796",
        negara_asal: "Rusia",
        bidang_keahlian: "Pemerintahan, Diplomasi",
        kontribusi_utama: "Perluasan Rusia, Pencerahan Rusia",
        pencapaian_penting: ["Perluasan Rusia Besar", "Reformasi Pencerahan", "Kekuatan Rusia"],
        pengaruh_sejarah: "Membuat Rusia menjadi kekuatan Eropa besar",
        legacy: "Permaisuri Rusia terbesar",
        sumber_referensi: ["Catherine the Great", "The Life of Catherine II"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Frederick the Great",
        deskripsi_tokoh: "Frederick II (1712-1786) adalah raja Prusia yang memperluas Prusia melalui perang dan diplomasi. Dia adalah pemikir pencerahan dan reformis administrasi.",
        periode_hidup: "1712-1786",
        negara_asal: "Prusia (Jerman)",
        bidang_keahlian: "Pemerintahan, Militer, Filosofi",
        kontribusi_utama: "Perluasan Prusia, Reformasi Pencerahan",
        pencapaian_penting: ["Perluasan Prusia Besar", "Filsafat Pencerahan", "Kemenangan Militer"],
        pengaruh_sejarah: "Membuat Prusia menjadi kekuatan Eropa utama",
        legacy: "Raja Prusia terbesar",
        sumber_referensi: ["Frederick the Great", "The Life of Frederick II"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Louis XVI",
        deskripsi_tokoh: "Louis XVI (1754-1793) adalah raja Perancis pada saat Revolusi Perancis. Ketidakmampuannya mengelola krisis menyebabkan jatuhnya monarki Perancis absolut.",
        periode_hidup: "1754-1793",
        negara_asal: "Perancis",
        bidang_keahlian: "Pemerintahan",
        kontribusi_utama: "Pemerintahan Perancis pada era Revolusi",
        pencapaian_penting: ["Dukungan Perang Kemerdekaan Amerika", "Konstitusi Perancis", "Eksekusi"],
        pengaruh_sejarah: "Jatuhnya monarki absolut Perancis",
        legacy: "Raja terakhir Perancis absolut",
        sumber_referensi: ["Marie Antoinette and Louis XVI", "The French Revolution"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Robespierre",
        deskripsi_tokoh: "Maximilien Robespierre (1758-1794) adalah pemimpin Revolusi Perancis yang memimpin Periode Teror. Dia mewakili prinsip-prinsip Revolusi namun dengan cara yang radikal dan ekstrem.",
        periode_hidup: "1758-1794",
        negara_asal: "Perancis",
        bidang_keahlian: "Politik, Revolusi",
        kontribusi_utama: "Kepemimpinan Revolusi Perancis, Periode Teror",
        pencapaian_penting: ["Kepemimpinan Komite Keselamatan Publik", "Periode Teror", "Eksekusi Raja"],
        pengaruh_sejarah: "Memimpin fase radikal Revolusi Perancis",
        legacy: "Simbol Revolusi Perancis",
        sumber_referensi: ["Robespierre", "The Reign of Terror"],
        kategori: "Pemimpin Revolusi"
      },
      {
        nama_tokoh: "Hideki Tojo",
        deskripsi_tokoh: "Hideki Tojo (1884-1948) adalah jenderal dan perdana menteri Jepang yang memimpin Jepang selama Perang Dunia II. Dia diadili sebagai penjahat perang setelah kekalahannya.",
        periode_hidup: "1884-1948",
        negara_asal: "Jepang",
        bidang_keahlian: "Militer, Pemerintahan",
        kontribusi_utama: "Kepemimpinan Jepang dalam Perang Dunia II",
        pencapaian_penting: ["Serangan Pearl Harbor", "Pemerintahan Jepang", "Pengadilan Penjahat Perang"],
        pengaruh_sejarah: "Memimpin Jepang dalam Perang Dunia II",
        legacy: "Pemimpin kontroversial dalam sejarah Jepang",
        sumber_referensi: ["The Trial of Hideki Tojo", "World War II Japan"],
        kategori: "Pemimpin Militer"
      },
      {
        nama_tokoh: "Rani of Jhansi",
        deskripsi_tokoh: "Rani of Jhansi (1828-1858) adalah ratu India yang memimpin perlawanan terhadap Kerajaan Inggris dalam Pemberontakan India 1857. Dia adalah simbol keberanian perempuan India.",
        periode_hidup: "1828-1858",
        negara_asal: "India",
        bidang_keahlian: "Perlawanan, Militer",
        kontribusi_utama: "Perlawanan terhadap penjajahan Inggris",
        pencapaian_penting: ["Pemberontakan India 1857", "Kepemimpinan Militer", "Simbol Keberanian"],
        pengaruh_sejarah: "Menginspirasi perlawanan India terhadap penjajahan",
        legacy: "Simbol keberanian dan nasionalisme India",
        sumber_referensi: ["The Rani of Jhansi", "Women Warriors in India"],
        kategori: "Pahlawan Nasional"
      },
      {
        nama_tokoh: "Socrates (Filsof Yunani)",
        deskripsi_tokoh: "Socrates adalah pelopor filsafat Barat dengan metode dialektis yang mencari kebenaran melalui pertanyaan.",
        periode_hidup: "470-399 SM",
        negara_asal: "Yunani",
        bidang_keahlian: "Filsafat, Logika",
        kontribusi_utama: "Metode Socratic, Filsafat Moral",
        pencapaian_penting: ["Metode Socratic", "Teori Kebajikan", "Pengaruh pada Plato"],
        pengaruh_sejarah: "Pendiri filsafat Barat modern",
        legacy: "Bapak filsafat Barat",
        sumber_referensi: ["Apology", "Phaedo"],
        kategori: "Filsuf"
      },
      {
        nama_tokoh: "Zoroaster",
        deskripsi_tokoh: "Zoroaster (660-583 SM) adalah nabi Persia yang mendirikan Zoroastrianisme, agama monoteistik tertua di dunia yang mempengaruhi Judaisme, Kristen, dan Islam.",
        periode_hidup: "660-583 SM",
        negara_asal: "Persia",
        bidang_keahlian: "Spiritualitas, Agama",
        kontribusi_utama: "Zoroastrianisme, Monoteisme Awal",
        pencapaian_penting: ["Agama Zoroaster", "Dualisme Baik-Buruk", "Pengaruh pada Agama Abrahamik"],
        pengaruh_sejarah: "Agama monoteistik tertua yang mempengaruhi agama Abrahamik",
        legacy: "Pendiri Zoroastrianisme",
        sumber_referensi: ["The Avesta", "Zoroastrianism by Mary Boyce"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Stephen Hawking",
        deskripsi_tokoh: "Stephen Hawking (1942-2018) adalah fisikawan teoritis yang mengungkap misteri lubang hitam dan asal-usul alam semesta meskipun mengalami penyakit motor neuron.",
        periode_hidup: "1942-2018",
        negara_asal: "Inggris",
        bidang_keahlian: "Fisika Teoritis, Kosmologi",
        kontribusi_utama: "Radiasi Hawking, Lubang Hitam",
        pencapaian_penting: ["Radiasi Hawking", "Brief History of Time", "Teori Lubang Hitam"],
        pengaruh_sejarah: "Merevolusi pemahaman kosmologi modern",
        legacy: "Fisikawan teoritis terbesar abad 20",
        sumber_referensi: ["A Brief History of Time", "Hawking by John Boslough"],
        kategori: "Ilmuwan"
      },
      {
        nama_tokoh: "Nikola Tesla",
        deskripsi_tokoh: "Nikola Tesla (1856-1943) adalah insinyur dan pencipta Serbia yang mengembangkan sistem arus bolak-balik dan wireless transmission. Dia adalah visioner teknologi modern.",
        periode_hidup: "1856-1943",
        negara_asal: "Serbia",
        bidang_keahlian: "Teknik Elektrik, Inovasi",
        kontribusi_utama: "Arus Bolak-balik, Wireless Transmission",
        pencapaian_penting: ["Sistem AC", "Transmisi Nirkabel", "Invensi Elektrik"],
        pengaruh_sejarah: "Merevolusi industri listrik dan telekomunikasi",
        legacy: "Visioner teknologi modern",
        sumber_referensi: ["Tesla: The Man Behind the Lightning", "My Inventions"],
        kategori: "Ilmuwan dan Penemu"
      },
      {
        nama_tokoh: "Franklin Delano Roosevelt",
        deskripsi_tokoh: "FDR (1882-1945) adalah presiden Amerika ke-32 yang memimpin negara melalui Depresi Besar dan Perang Dunia II. Dia memperkuat peran pemerintah dalam kehidupan ekonomi.",
        periode_hidup: "1882-1945",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Pemerintahan, Ekonomi",
        kontribusi_utama: "New Deal, Kepemimpinan Perang Dunia II",
        pencapaian_penting: ["New Deal", "Perang Dunia II", "Social Security"],
        pengaruh_sejarah: "Membentuk peran pemerintah modern",
        legacy: "Presiden paling berpengaruh abad 20",
        sumber_referensi: ["FDR by Jean Edward Smith", "Franklin Delano Roosevelt"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Rosa Parks",
        deskripsi_tokoh: "Rosa Parks (1913-2005) adalah aktivis sipil Amerika yang menolak menyerah tempat duduknya kepada penumpang kulit putih, memicu Bus Boycott Montgomery.",
        periode_hidup: "1913-2005",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Gerakan Hak Sipil",
        kontribusi_utama: "Bus Boycott Montgomery, Hak Sipil",
        pencapaian_penting: ["Penolakan Duduk di Bus", "Bus Boycott Montgomery", "Aktivisme Sipil"],
        pengaruh_sejarah: "Memicu gerakan hak sipil modern",
        legacy: "Simbol perlawanan rasial",
        sumber_referensi: ["The Autobiography of Rosa Parks", "Rosa Parks"],
        kategori: "Aktivis Hak Sipil"
      },
      {
        nama_tokoh: "Aung San Suu Kyi",
        deskripsi_tokoh: "Aung San Suu Kyi (lahir 1945) adalah pemimpin demokrasi Myanmar yang memenangkan Nobel Peace Prize untuk perjuangan melawan junta militer.",
        periode_hidup: "1945-Sekarang",
        negara_asal: "Myanmar",
        bidang_keahlian: "Perlawanan Demokrasi",
        kontribusi_utama: "Perlawanan terhadap junta militer, Demokrasi Myanmar",
        pencapaian_penting: ["Perlawanan Junta Militer", "Nobel Peace Prize", "Demokrasi Myanmar"],
        pengaruh_sejarah: "Simbol perlawanan demokrasi di Asia",
        legacy: "Pemimpin demokrasi yang dihormati",
        sumber_referensi: ["The Lady", "Aung San Suu Kyi"],
        kategori: "Pemimpin Demokrasi"
      },
      {
        nama_tokoh: "Malala Yousafzai",
        deskripsi_tokoh: "Malala Yousafzai (lahir 1997) adalah aktivis pendidikan Pakistan yang ditembak oleh Taliban namun terus memperjuangkan hak pendidikan anak perempuan.",
        periode_hidup: "1997-Sekarang",
        negara_asal: "Pakistan",
        bidang_keahlian: "Pendidikan, Aktivisme",
        kontribusi_utama: "Hak Pendidikan Anak Perempuan",
        pencapaian_penting: ["Perjuangan Pendidikan", "Nobel Peace Prize Termuda", "Aktivisme Global"],
        pengaruh_sejarah: "Menginspirasi gerakan pendidikan global",
        legacy: "Simbol perjuangan pendidikan anak perempuan",
        sumber_referensi: ["I Am Malala", "Malala Yousafzai"],
        kategori: "Aktivis Pendidikan"
      },
      {
        nama_tokoh: "Steve Jobs",
        deskripsi_tokoh: "Steve Jobs (1955-2011) adalah pendiri Apple dan visioner teknologi yang merevolusi industri komputer personal, musik digital, dan ponsel pintar.",
        periode_hidup: "1955-2011",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Teknologi, Inovasi",
        kontribusi_utama: "Apple, iPhone, iPad, Desain User Interface",
        pencapaian_penting: ["Apple Computer", "iPhone", "iPad", "Desain Produk"],
        pengaruh_sejarah: "Merevolusi industri teknologi konsumen",
        legacy: "Visioner teknologi era digital",
        sumber_referensi: ["Jobs by Walter Isaacson", "The Steve Jobs Story"],
        kategori: "Entrepreneur"
      },
      {
        nama_tokoh: "Bill Gates",
        deskripsi_tokoh: "Bill Gates (lahir 1955) adalah pendiri Microsoft yang membangun imperium software dan kemudian menjadi filantropis kesehatan global melalui Bill & Melinda Gates Foundation.",
        periode_hidup: "1955-Sekarang",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Software, Filantropi",
        kontribusi_utama: "Microsoft, Filantropi Kesehatan",
        pencapaian_penting: ["Microsoft", "Windows", "Global Health Initiatives"],
        pengaruh_sejarah: "Merevolusi industri software, filantropi global",
        legacy: "Entrepreneur dan filantropis terbesar",
        sumber_referensi: ["The Road Ahead", "Bill Gates Biography"],
        kategori: "Entrepreneur dan Filantropis"
      },
      {
        nama_tokoh: "Elon Musk",
        deskripsi_tokoh: "Elon Musk (lahir 1971) adalah entrepreneur visioner yang mendirikan Tesla, SpaceX, dan Neuralink, merevol usionisasi industri otomotif, antariksa, dan neurotekhnologi.",
        periode_hidup: "1971-Sekarang",
        negara_asal: "Afrika Selatan/Amerika",
        bidang_keahlian: "Teknologi, Inovasi, Antariksa",
        kontribusi_utama: "Tesla, SpaceX, Kendaraan Listrik Revolusioner",
        pencapaian_penting: ["Tesla", "SpaceX", "Roket Reusable", "Kendaraan Listrik"],
        pengaruh_sejarah: "Merevolusi industri otomotif dan antariksa",
        legacy: "Visioner teknologi kontemporer",
        sumber_referensi: ["Elon Musk by Walter Isaacson", "Ashlee Vance"],
        kategori: "Entrepreneur"
      },
      {
        nama_tokoh: "Marie Antoinette",
        deskripsi_tokoh: "Marie Antoinette (1755-1793) adalah ratu Perancis yang menjadi simbol kemewahan monarki sebelum dieksekusi pada Revolusi Perancis.",
        periode_hidup: "1755-1793",
        negara_asal: "Austria/Perancis",
        bidang_keahlian: "Pemerintahan Monarki",
        kontribusi_utama: "Pemerintahan Monarki Perancis",
        pencapaian_penting: ["Ratu Perancis", "Eksekusi Revolusi", "Simbol Monarki"],
        pengaruh_sejarah: "Simbol jatuhnya monarki absolut",
        legacy: "Ratu yang tragis dalam sejarah",
        sumber_referensi: ["Marie Antoinette by Antonia Fraser", "The Diamond Necklace Affair"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Sigmund Freud",
        deskripsi_tokoh: "Sigmund Freud (1856-1939) adalah psikolog Austria yang mengembangkan psikoanalisis dan teori unconscious mind, merevolusi pemahaman psikologi manusia.",
        periode_hidup: "1856-1939",
        negara_asal: "Austria",
        bidang_keahlian: "Psikologi, Psikoanalisis",
        kontribusi_utama: "Psikoanalisis, Teori Unconscious",
        pencapaian_penting: ["Psikoanalisis", "Teori Kepribadian", "Interpretation of Dreams"],
        pengaruh_sejarah: "Merevolusi pemahaman psikologi modern",
        legacy: "Bapak psikoanalisis",
        sumber_referensi: ["The Interpretation of Dreams", "Sigmund Freud by Peter Gay"],
        kategori: "Psikolog"
      },
      {
        nama_tokoh: "Carl Jung",
        deskripsi_tokoh: "Carl Jung (1875-1961) adalah psikolog Swiss yang mengembangkan teori analitik psikologi dan konsep archetypes, unconscious kolektif, dan tipe kepribadian.",
        periode_hidup: "1875-1961",
        negara_asal: "Swiss",
        bidang_keahlian: "Psikologi, Analitik",
        kontribusi_utama: "Psikologi Analitik, Archetypes, Tipe Kepribadian",
        pencapaian_penting: ["Psikologi Analitik", "Unconscious Kolektif", "Myers-Briggs Type"],
        pengaruh_sejarah: "Merevolusi psikologi dalam memahami kepribadian",
        legacy: "Bapak psikologi analitik",
        sumber_referensi: ["Psychology and Religion", "Carl Jung by Anthony Stevens"],
        kategori: "Psikolog"
      },
      {
        nama_tokoh: "Florence Nightingale",
        deskripsi_tokoh: "Florence Nightingale (1820-1910) adalah perawat Inggris pionir yang merevolusi perawatan kesehatan dan sanitasi di rumah sakit modern.",
        periode_hidup: "1820-1910",
        negara_asal: "Inggris",
        bidang_keahlian: "Perawatan Kesehatan, Nursing",
        kontribusi_utama: "Reformasi Perawatan Kesehatan, Nursing Modern",
        pencapaian_penting: ["Perawatan Perang Crimea", "Reformasi Rumah Sakit", "Pendidikan Nursing"],
        pengaruh_sejarah: "Mendirikan profesion nursing modern",
        legacy: "Pendiri nursing modern",
        sumber_referensi: ["Notes on Nursing", "Florence Nightingale by Cecil Woodham-Smith"],
        kategori: "Tokoh Kesehatan"
      },
      {
        nama_tokoh: "Harriet Tubman",
        deskripsi_tokoh: "Harriet Tubman (1820-1913) adalah perempuan Afrika-Amerika yang melarikan diri dari perbudakan dan membantu ratusan budak lainnya melarikan diri melalui Underground Railroad.",
        periode_hidup: "1820-1913",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Perlawanan Perbudakan",
        kontribusi_utama: "Underground Railroad, Pembebasan Budak",
        pencapaian_penting: ["Underground Railroad", "Pembebasan Budak", "Kepemimpinan Militer Sipil"],
        pengaruh_sejarah: "Menginspirasi perlawanan terhadap perbudakan",
        legacy: "Pahlawan pembebasan budak",
        sumber_referensi: ["The Life of Harriet Tubman", "Harriet Tubman: The Road to Freedom"],
        kategori: "Aktivis Pembebasan"
      },
      {
        nama_tokoh: "Eleanor Roosevelt",
        deskripsi_tokoh: "Eleanor Roosevelt (1884-1962) adalah Ibu Negara Amerika yang menjadi advokat hak asasi manusia, kesetaraan gender, dan keadilan sosial.",
        periode_hidup: "1884-1962",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Hak Asasi Manusia, Advokasi",
        kontribusi_utama: "Universal Declaration of Human Rights",
        pencapaian_penting: ["UDHR", "Hak Asasi Manusia", "Kesetaraan Gender"],
        pengaruh_sejarah: "Merevolusi pemahaman hak asasi manusia global",
        legacy: "Advokat hak asasi manusia terbesar",
        sumber_referensi: ["My Day", "Eleanor Roosevelt by Blanche Wiesen Cook"],
        kategori: "Advokat Hak Asasi"
      },
      {
        nama_tokoh: "Anne Frank",
        deskripsi_tokoh: "Anne Frank (1929-1945) adalah gadis Yahudi yang menyembunyikan diri dari Nazi di Amsterdam dan menulis jurnal yang menjadi simbol Holocaust.",
        periode_hidup: "1929-1945",
        negara_asal: "Belanda",
        bidang_keahlian: "Sejarah, Testimonial",
        kontribusi_utama: "Testimoni Holocaust, The Diary of Anne Frank",
        pencapaian_penting: ["Jurnal Tersembunyi", "Testimoni Holocaust", "Simbol Harapan"],
        pengaruh_sejarah: "Menginspirasi kesadaran Holocaust global",
        legacy: "Simbol korban Holocaust",
        sumber_referensi: ["The Diary of Anne Frank", "Hidden Children"],
        kategori: "Tokoh Sejarah"
      },
      {
        nama_tokoh: "Che Guevara",
        deskripsi_tokoh: "Che Guevara (1928-1967) adalah revolusioner Argentina yang memimpin gerakan revolusi di Kuba dan Amerika Latin melawan imperialisme.",
        periode_hidup: "1928-1967",
        negara_asal: "Argentina",
        bidang_keahlian: "Revolusi, Perlawanan",
        kontribusi_utama: "Revolusi Kuba, Gerakan Anti-Imperialisme",
        pencapaian_penting: ["Revolusi Kuba", "Gerakan Bolivia", "Simbol Perlawanan"],
        pengaruh_sejarah: "Menginspirasi gerakan revolusi global",
        legacy: "Ikon revolusi abad 20",
        sumber_referensi: ["The Motorcycle Diaries", "Che Guevara: A Revolutionary Life"],
        kategori: "Revolusioner"
      },
      {
        nama_tokoh: "Osama bin Laden",
        deskripsi_tokoh: "Osama bin Laden (1957-2011) adalah terrorist yang mendirikan Al-Qaeda dan merencanakan serangan 11 September 2001 terhadap Amerika Serikat.",
        periode_hidup: "1957-2011",
        negara_asal: "Arab Saudi",
        bidang_keahlian: "Terorisme, Perang Asimetris",
        kontribusi_utama: "Al-Qaeda, Serangan 11 September",
        pencapaian_penting: ["Serangan 11 September", "Perang Global terhadap Terorisme", "Pembunuhan oleh SEAL Team Six"],
        pengaruh_sejarah: "Mengubah geopolitik global pasca-2001",
        legacy: "Ikon terorisme global",
        sumber_referensi: ["The 9/11 Commission Report", "Osama bin Laden by Peter Bergen"],
        kategori: "Terrorist"
      },
      {
        nama_tokoh: "Moses",
        deskripsi_tokoh: "Moses (1400-1200 SM) adalah nabi Yudaisme yang memimpin Keluaran orang Israel dari Mesir dan menerima Sepuluh Perintah. Dia adalah tokoh pusat dalam Taurat dan Alkitab.",
        periode_hidup: "1400-1200 SM",
        negara_asal: "Mesir/Kanaan",
        bidang_keahlian: "Spiritualitas, Pimpinan Agama",
        kontribusi_utama: "Yudaisme, Hukum Mosaik",
        pencapaian_penting: ["Keluaran dari Mesir", "Sepuluh Perintah", "Taurat"],
        pengaruh_sejarah: "Pendiri tradisi Yudaisme, mempengaruhi Kristen dan Islam",
        legacy: "Nabi dan pemimpin Yudaisme",
        sumber_referensi: ["The Torah", "Life of Moses"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Margaret Thatcher",
        deskripsi_tokoh: "Margaret Thatcher (1925-2013) adalah Perdana Menteri Inggris pertama perempuan yang menerapkan kebijakan konservatif radikal (Thatcherism).",
        periode_hidup: "1925-2013",
        negara_asal: "Inggris",
        bidang_keahlian: "Pemerintahan, Politik Konservatif",
        kontribusi_utama: "Thatcherism, Reformasi Ekonomi Inggris",
        pencapaian_penting: ["Kepemimpinan Perempuan", "Perang Falkland", "Reformasi Ekonomi"],
        pengaruh_sejarah: "Mengubah ekonomi Inggris dan Barat",
        legacy: "Pemimpin perempuan paling berpengaruh abad 20",
        sumber_referensi: ["The Path to Power", "Margaret Thatcher by Hugo Young"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Mikhail Gorbachev",
        deskripsi_tokoh: "Mikhail Gorbachev (1931-2022) adalah pemimpin terakhir Uni Soviet yang menerapkan glasnost dan perestroika, menyebabkan keruntuhan Uni Soviet.",
        periode_hidup: "1931-2022",
        negara_asal: "Uni Soviet",
        bidang_keahlian: "Pemerintahan, Reformasi",
        kontribusi_utama: "Glasnost, Perestroika, Akhir Perang Dingin",
        pencapaian_penting: ["Glasnost", "Perestroika", "Akhir Perang Dingin", "Nobel Peace Prize"],
        pengaruh_sejarah: "Mengakhiri Perang Dingin dan Uni Soviet",
        legacy: "Pemimpin yang mengakhiri Perang Dingin",
        sumber_referensi: ["Memoirs of Mikhail Gorbachev", "Gorbachev by William Taubman"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Ronald Reagan",
        deskripsi_tokoh: "Ronald Reagan (1911-2004) adalah presiden Amerika ke-40 yang memimpin perang frontal melawan Uni Soviet, mempercepat akhir Perang Dingin.",
        periode_hidup: "1911-2004",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Pemerintahan, Politika Anti-Komunis",
        kontribusi_utama: "Perang Dingin, Reformasi Konservatif",
        pencapaian_penting: ["Perang Dingin", "Reformasi Konservatif", "Ekonomi Reaganomics"],
        pengaruh_sejarah: "Mempercepat akhir Perang Dingin",
        legacy: "Presiden konservatif paling berpengaruh",
        sumber_referensi: ["An American Life", "Reagan by Edmund Morris"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "John F. Kennedy",
        deskripsi_tokoh: "John F. Kennedy (1917-1963) adalah presiden Amerika termuda yang ditembak dan terbunuh pada 1963. Dia memimpin Amerika melalui Krisis Misil Kuba.",
        periode_hidup: "1917-1963",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Pemerintahan, Diplomasi",
        kontribusi_utama: "Krisis Misil Kuba, Program Luar Angkasa",
        pencapaian_penting: ["Krisis Misil Kuba", "Program Apollo", "Penghapusan Diskriminasi"],
        pengaruh_sejarah: "Memimpin Amerika melalui krisis nuklir",
        legacy: "Presiden legendaris dan martir",
        sumber_referensi: ["JFK by Peter Collier", "Thirteen Days"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Indira Gandhi",
        deskripsi_tokoh: "Indira Gandhi (1917-1984) adalah Perdana Menteri India pertama dan perempuan yang memimpin India selama 15 tahun dengan kebijakan sosialisme dan kemandirian ekonomi.",
        periode_hidup: "1917-1984",
        negara_asal: "India",
        bidang_keahlian: "Pemerintahan, Sosialisme",
        kontribusi_utama: "Sosialisme India, Kemandirian Ekonomi",
        pencapaian_penting: ["Sosialisme India", "Revolusi Hijau", "Kemandirian Energi Nuklir"],
        pengaruh_sejarah: "Membentuk India modern sosialis",
        legacy: "Perdana Menteri perempuan paling berpengaruh Asia",
        sumber_referensi: ["The Autobiography of Indira Gandhi", "Indira Gandhi by Kuldip Nayar"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Jawaharlal Nehru",
        deskripsi_tokoh: "Jawaharlal Nehru (1889-1964) adalah Perdana Menteri India pertama yang memimpin India menuju modernisasi dan industrialisasi pasca-kemerdekaan.",
        periode_hidup: "1889-1964",
        negara_asal: "India",
        bidang_keahlian: "Pemerintahan, Modernisasi",
        kontribusi_utama: "Kemerdekaan India, Modernisasi Ekonomi",
        pencapaian_penting: ["Perdana Menteri Pertama", "Modernisasi India", "Demokrasi India"],
        pengaruh_sejarah: "Membentuk India modern independen",
        legacy: "Arsitek India modern",
        sumber_referensi: ["The Discovery of India", "Jawaharlal Nehru by Katherine Frank"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Deng Xiaoping",
        deskripsi_tokoh: "Deng Xiaoping (1904-1997) adalah pemimpin Cina yang mengimplementasikan reformasi ekonomi pasar yang mentransformasi Cina menjadi kekuatan ekonomi global.",
        periode_hidup: "1904-1997",
        negara_asal: "Cina",
        bidang_keahlian: "Pemerintahan, Ekonomi",
        kontribusi_utama: "Reformasi Ekonomi Cina, 'Socialism with Chinese Characteristics'",
        pencapaian_penting: ["Reformasi Ekonomi", "Zona Ekonomi Khusus", "Transformasi Cina"],
        pengaruh_sejarah: "Mentransformasi Cina menjadi kekuatan ekonomi",
        legacy: "Arsitek Cina modern",
        sumber_referensi: ["Deng Xiaoping and the Making of Modern China", "Deng Xiaoping by Ezra Vogel"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Mao Zedong",
        deskripsi_tokoh: "Mao Zedong (1893-1976) adalah pendiri Komunisme Cina dan pemimpin pertama Republik Rakyat Cina. Pemerintahannya ditandai dengan kemajuan industri dan tragedi kemanusiaan.",
        periode_hidup: "1893-1976",
        negara_asal: "Cina",
        bidang_keahlian: "Pemerintahan, Komunisme",
        kontribusi_utama: "Komunisme Cina, Industrialisasi Cina",
        pencapaian_penting: ["Revolusi Komunis", "Great Leap Forward", "Industrialisasi"],
        pengaruh_sejarah: "Mentransformasi Cina menjadi komunis",
        legacy: "Pemimpin Cina paling berpengaruh abad 20",
        sumber_referensi: ["Mao: A Life by Philip Short", "The Unknown Story"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Ho Chi Minh",
        deskripsi_tokoh: "Ho Chi Minh (1890-1969) adalah pemimpin Vietnam yang mempersatukan Vietnam dan memimpin perjuangan melawan Perancis dan Amerika Serikat.",
        periode_hidup: "1890-1969",
        negara_asal: "Vietnam",
        bidang_keahlian: "Perlawanan Kolonial, Komunisme",
        kontribusi_utama: "Kemerdekaan Vietnam, Perang Vietnam",
        pencapaian_penting: ["Kemerdekaan Vietnam", "Perang Perancis-Indochina", "Penyatuan Vietnam"],
        pengaruh_sejarah: "Memimpin Vietnam menuju kemerdekaan",
        legacy: "Pahlawan nasional Vietnam",
        sumber_referensi: ["Ho Chi Minh: A Life", "Selected Writings"],
        kategori: "Pemimpin Perlawanan"
      },
      {
        nama_tokoh: "Fidel Castro",
        deskripsi_tokoh: "Fidel Castro (1926-2016) adalah pemimpin revolusi Kuba yang menggulingkan Batista dan memimpin Kuba sebagai negara komunis selama 48 tahun.",
        periode_hidup: "1926-2016",
        negara_asal: "Kuba",
        bidang_keahlian: "Revolusi, Komunisme",
        kontribusi_utama: "Revolusi Kuba, Komunisme Amerika Latin",
        pencapaian_penting: ["Revolusi Kuba", "Krisis Misil Kuba", "Pemerintahan 48 Tahun"],
        pengaruh_sejarah: "Membawa komunisme ke Amerika",
        legacy: "Revolusioner abad 20 paling kontroversial",
        sumber_referensi: ["The Autobiography of Fidel Castro", "Fidel: A Biography"],
        kategori: "Revolusioner"
      },
      {
        nama_tokoh: "Kwame Nkrumah",
        deskripsi_tokoh: "Kwame Nkrumah (1909-1972) adalah pemimpin Ghana yang mempimpin kemerdekaan Ghana dari Inggris dan adalah pelopor Pan-Africanism.",
        periode_hidup: "1909-1972",
        negara_asal: "Ghana",
        bidang_keahlian: "Kemerdekaan Afrika, Pan-Africanism",
        kontribusi_utama: "Kemerdekaan Ghana, Pan-Africanism",
        pencapaian_penting: ["Kemerdekaan Ghana", "Pan-Africanism", "Pemerintahan Sosialis"],
        pengaruh_sejarah: "Menginspirasi dekolonisasi Afrika",
        legacy: "Bapak dekolonisasi Afrika",
        sumber_referensi: ["Ghana: The Autobiography of Kwame Nkrumah", "The Positive Action"],
        kategori: "Pemimpin Dekolonisasi"
      },
      {
        nama_tokoh: "Julius Nyerere",
        deskripsi_tokoh: "Julius Nyerere (1922-1999) adalah pemimpin Tanzania yang mempimpin kemerdekaan Tanganyika dan Zanzibar, menciptakan Tanzania modern.",
        periode_hidup: "1922-1999",
        negara_asal: "Tanzania",
        bidang_keahlian: "Kemerdekaan, Pan-Africanism",
        kontribusi_utama: "Kemerdekaan Tanzania, Ujamaa Sosialisme",
        pencapaian_penting: ["Kemerdekaan Tanganyika", "Penyatuan Tanzania", "Ujamaa"],
        pengaruh_sejarah: "Memimpin dekolonisasi Afrika Timur",
        legacy: "Bapak Tanzania modern",
        sumber_referensi: ["Julius Nyerere: A Man of Principle", "Tanzania: The Visionary"],
        kategori: "Pemimpin Dekolonisasi"
      },
      {
        nama_tokoh: "Jomo Kenyatta",
        deskripsi_tokoh: "Jomo Kenyatta (1895-1978) adalah pemimpin Kenya yang mempimpin kemerdekaan Kenya dari Inggris dan menjadi presiden pertama Kenya selama 14 tahun.",
        periode_hidup: "1895-1978",
        negara_asal: "Kenya",
        bidang_keahlian: "Kemerdekaan, Pemerintahan",
        kontribusi_utama: "Kemerdekaan Kenya, Pemerintahan Kenya",
        pencapaian_penting: ["Kemerdekaan Kenya", "Presiden Kenya", "Stabilitas Afrika Timur"],
        pengaruh_sejarah: "Memimpin dekolonisasi Kenya",
        legacy: "Bapak Kenya modern",
        sumber_referensi: ["Jomo Kenyatta: Facing Mount Kenya", "The Father of Kenya"],
        kategori: "Pemimpin Dekolonisasi"
      },
      {
        nama_tokoh: "Haile Selassie",
        deskripsi_tokoh: "Haile Selassie (1892-1975) adalah Negus (Kaisar) Etiopia yang mempertahankan kemerdekaan Etiopia dari penjajahan Italia dan simbol anti-imperialisme Afrika.",
        periode_hidup: "1892-1975",
        negara_asal: "Etiopia",
        bidang_keahlian: "Pemerintahan, Anti-Imperialisme",
        kontribusi_utama: "Kemerdekaan Etiopia, Anti-Imperialisme Afrika",
        pencapaian_penting: ["Pertahanan Etiopia dari Italia", "Liga Bangsa-Bangsa", "Simbol Pan-Africanism"],
        pengaruh_sejarah: "Simbol anti-imperialisme Afrika",
        legacy: "Kaisar Etiopia legendaris",
        sumber_referensi: ["Haile Selassie I: His Imperial Majesty", "When the Negus Ruled"],
        kategori: "Pemimpin Negara"
      },
      {
        nama_tokoh: "Salvador Allende",
        deskripsi_tokoh: "Salvador Allende (1908-1973) adalah presiden Chile pertama yang terpilih secara demokratis dengan platform sosialis, namun dijatuhkan oleh kudeta militer Pinochet.",
        periode_hidup: "1908-1973",
        negara_asal: "Chile",
        bidang_keahlian: "Sosialisme Demokratis",
        kontribusi_utama: "Sosialisme Demokratis, Reformasi Chile",
        pencapaian_penting: ["Presiden Sosialis Terpilih", "Reformasi Sosial", "Perlawanan Kudeta"],
        pengaruh_sejarah: "Simbol sosialisme demokratis di Amerika Latin",
        legacy: "Martir sosialisme Amerika Latin",
        sumber_referensi: ["Salvador Allende by Jonathan Haslam", "The Other 9/11"],
        kategori: "Pemimpin Politik"
      },
      {
        nama_tokoh: "Augusto Pinochet",
        deskripsi_tokoh: "Augusto Pinochet (1915-2006) adalah jenderal Chile yang melakukan kudeta terhadap Allende dan memimpin diktatur militer Chile selama 17 tahun.",
        periode_hidup: "1915-2006",
        negara_asal: "Chile",
        bidang_keahlian: "Militer, Diktatur",
        kontribusi_utama: "Kudeta Chile, Reformasi Ekonomi",
        pencapaian_penting: ["Kudeta 1973", "Diktatur Militer", "Reformasi Ekonomi Neoliberal"],
        pengaruh_sejarah: "Diktator kontroversial Amerika Latin",
        legacy: "Simbol diktatur militer dan pelanggaran HAM",
        sumber_referensi: ["Pinochet: The Politics of Torture", "The Pinochet File"],
        kategori: "Diktator"
      },
      {
        nama_tokoh: "Subhas Chandra Bose",
        deskripsi_tokoh: "Subhas Chandra Bose (1897-1945) adalah pemimpin India yang memimpikan kemerdekaan melalui perlawanan bersenjata dan bekerja sama dengan Jepang melawan Inggris.",
        periode_hidup: "1897-1945",
        negara_asal: "India",
        bidang_keahlian: "Perlawanan Kemerdekaan",
        kontribusi_utama: "Gerakan Kemerdekaan India, Indian National Army",
        pencapaian_penting: ["Indian National Army", "Perlawanan Bersenjata", "Simbol Kemerdekaan"],
        pengaruh_sejarah: "Pemimpin perlawanan India alternatif",
        legacy: "Pahlawan nasional India",
        sumber_referensi: ["Subhas Chandra Bose: A Rebel's Tale", "An Indian Pilgrim"],
        kategori: "Pemimpin Perlawanan"
      },
      {
        nama_tokoh: "Thich Quang Duc",
        deskripsi_tokoh: "Thich Quang Duc (1897-1963) adalah bhiksu Buddha Vietnam yang melakukan self-immolation untuk memprotes penganiayaan agama Buddha di Vietnam Selatan.",
        periode_hidup: "1897-1963",
        negara_asal: "Vietnam",
        bidang_keahlian: "Protesta Sipil, Agama",
        kontribusi_utama: "Protesta terhadap Diskriminasi Agama",
        pencapaian_penting: ["Self-Immolation", "Protesta Sipil", "Simbol Perlawanan"],
        pengaruh_sejarah: "Menginspirasi gerakan protesta sipil global",
        legacy: "Simbol perlawanan pasif",
        sumber_referensi: ["The Fire that Spoke", "Buddhist Resistance"],
        kategori: "Aktivis Sipil"
      },
      {
        nama_tokoh: "Martin Luther",
        deskripsi_tokoh: "Martin Luther (1483-1546) adalah reformator Protestan yang memicu Reformasi Protestan dengan kritiknya terhadap Gereja Katolik Roma dan penjualan indulgences.",
        periode_hidup: "1483-1546",
        negara_asal: "Jerman",
        bidang_keahlian: "Teologi, Reformasi Agama",
        kontribusi_utama: "Reformasi Protestan, Teologi Lutheran",
        pencapaian_penting: ["95 Tesis", "Reformasi Protestan", "Penterjemahan Alkitab"],
        pengaruh_sejarah: "Memicu Reformasi Protestan dan mengubah Kristen Barat",
        legacy: "Pendiri Protestantisme",
        sumber_referensi: ["Table Talk", "The Freedom of a Christian"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Emmeline Pankhurst",
        deskripsi_tokoh: "Emmeline Pankhurst (1858-1928) adalah pemimpin gerakan hak suara perempuan Inggris (suffragette) yang memperjuangkan hak memilih untuk perempuan.",
        periode_hidup: "1858-1928",
        negara_asal: "Inggris",
        bidang_keahlian: "Feminisme, Hak Suara",
        kontribusi_utama: "Gerakan Suffragette, Hak Suara Perempuan",
        pencapaian_penting: ["Suffragette Movement", "Hak Suara Perempuan", "Feminisme Awal"],
        pengaruh_sejarah: "Menginspirasi gerakan hak perempuan global",
        legacy: "Pemimpin feminisme awal",
        sumber_referensi: ["My Own Story", "Emmeline Pankhurst"],
        kategori: "Aktivis Feminisme"
      },
      {
        nama_tokoh: "Saint Augustine",
        deskripsi_tokoh: "Saint Augustine (354-430) adalah Bapak Gereja Katolik yang menulis 'Confessions' dan mengembangkan teologi Kristen yang mempengaruhi abad pertengahan.",
        periode_hidup: "354-430",
        negara_asal: "Afrika Utara (Aljazair)",
        bidang_keahlian: "Teologi, Filosofi, Spiritual",
        kontribusi_utama: "Teologi Kristen, Filosofi Agama",
        pencapaian_penting: ["Confessions", "Teologi Dosa dan Rahmat", "Filosofi Gereja"],
        pengaruh_sejarah: "Membentuk teologi Kristen selama berabad-abad",
        legacy: "Bapak Gereja dan teolog terbesar",
        sumber_referensi: ["Confessions", "City of God"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Simone de Beauvoir",
        deskripsi_tokoh: "Simone de Beauvoir (1908-1986) adalah filsuf dan penulis Perancis yang menulis 'The Second Sex' dan menjadi pionir feminisme kontemporer.",
        periode_hidup: "1908-1986",
        negara_asal: "Perancis",
        bidang_keahlian: "Filosofi, Feminisme",
        kontribusi_utama: "'The Second Sex', Feminisme Eksistensial",
        pencapaian_penting: ["The Second Sex", "Filosofi Feminisme", "Emansipasi Perempuan"],
        pengaruh_sejarah: "Merevolusi pemahaman feminisme modern",
        legacy: "Filosof feminisme terbesar abad 20",
        sumber_referensi: ["The Second Sex", "Simone de Beauvoir by Margaret Crosland"],
        kategori: "Filsof Feminisme"
      },
      {
        nama_tokoh: "Gloria Steinem",
        deskripsi_tokoh: "Gloria Steinem (lahir 1934) adalah aktivis feminisme Amerika yang memimpin Gerakan Perempuan modern pada tahun 1960an dan 1970an.",
        periode_hidup: "1934-Sekarang",
        negara_asal: "Amerika Serikat",
        bidang_keahlian: "Feminisme, Aktivisme",
        kontribusi_utama: "Gerakan Perempuan Modern, Feminisme",
        pencapaian_penting: ["Ms. Magazine", "Gerakan Perempuan 1970an", "Aktivisme Feminisme"],
        pengaruh_sejarah: "Memimpin gerakan perempuan modern",
        legacy: "Pemimpin feminisme abad 20",
        sumber_referensi: ["My Life on the Road", "Gloria Steinem Biography"],
        kategori: "Aktivis Feminisme"
      },
      {
        nama_tokoh: "Frida Kahlo",
        deskripsi_tokoh: "Frida Kahlo (1907-1954) adalah pelukis Meksiko yang mengeksplorasi identitas, penderitaan, dan kewanitaan melalui karya seni self-portraitnya yang ikonik.",
        periode_hidup: "1907-1954",
        negara_asal: "Meksiko",
        bidang_keahlian: "Seni, Lukisan",
        kontribusi_utama: "Karya Seni Ekspresif, Feminis dalam Seni",
        pencapaian_penting: ["Self-Portrait Ikonik", "Eksplorasi Identitas", "Seni Feminis"],
        pengaruh_sejarah: "Merevolusi seni kontemporer",
        legacy: "Seniman feminis terbesar abad 20",
        sumber_referensi: ["The Diary of Frida Kahlo", "Frida by Hayden Herrera"],
        kategori: "Seniman"
      },
      {
        nama_tokoh: "Pablo Picasso",
        deskripsi_tokoh: "Pablo Picasso (1881-1973) adalah pelukis Spanyol yang merevolusi seni modern dengan mengembangkan Kubisme dan menciptakan karya masterpiece seperti Guernica.",
        periode_hidup: "1881-1973",
        negara_asal: "Spanyol",
        bidang_keahlian: "Seni, Lukisan, Patung",
        kontribusi_utama: "Kubisme, Seni Modern",
        pencapaian_penting: ["Kubisme", "Guernica", "Inovasi Seni"],
        pengaruh_sejarah: "Merevolusi seni modern",
        legacy: "Seniman paling ikonik abad 20",
        sumber_referensi: ["Life of Picasso", "Picasso by William Rubin"],
        kategori: "Seniman"
      },
      {
        nama_tokoh: "Vincent van Gogh",
        deskripsi_tokoh: "Vincent van Gogh (1853-1890) adalah pelukis Belanda yang menciptakan karya masterpiece seperti Starry Night meskipun hidup dalam kemiskinan dan penyakit mental.",
        periode_hidup: "1853-1890",
        negara_asal: "Belanda",
        bidang_keahlian: "Seni, Lukisan",
        kontribusi_utama: "Ekspresionisme, Seni Impressionist",
        pencapaian_penting: ["Starry Night", "Sunflowers", "Ekspresionisme"],
        pengaruh_sejarah: "Merevolusi seni Impressionist modern",
        legacy: "Seniman paling berpengaruh dalam sejarah seni",
        sumber_referensi: ["The Letters of Vincent van Gogh", "Van Gogh by Steven Naifeh"],
        kategori: "Seniman"
      },
      {
        nama_tokoh: "Swami Vivekananda",
        deskripsi_tokoh: "Swami Vivekananda (1863-1902) adalah reformer spiritual Hindu India dan murid Ramakrishna Paramahamsa yang memperkenalkan Vedanta ke Barat.",
        periode_hidup: "1863-1902",
        negara_asal: "India",
        bidang_keahlian: "Spiritualitas, Hinduisme, Vedanta",
        kontribusi_utama: "Vedanta Modernisasi, Reformasi Hindu",
        pencapaian_penting: ["Parliament of Religions 1893", "Vedanta Kesadaran Global", "Reforma Hindu"],
        pengaruh_sejarah: "Membawa spiritualitas Hindu ke Barat modern",
        legacy: "Tokoh spiritual Hindu reformer",
        sumber_referensi: ["Complete Works of Swami Vivekananda", "Bhakti Yoga"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Rumi",
        deskripsi_tokoh: "Rumi (1207-1273) adalah penyair dan sufi Persia yang menulis puisi spiritual yang dalam tentang cinta, spiritualitas, dan transformasi spiritual.",
        periode_hidup: "1207-1273",
        negara_asal: "Persia",
        bidang_keahlian: "Spiritualitas, Puisi, Sufi",
        kontribusi_utama: "Puisi Sufi, Spiritualitas Cinta",
        pencapaian_penting: ["Masnavi", "Divan", "Spiritualitas Sufi"],
        pengaruh_sejarah: "Mempengaruhi spiritualitas Islam dan puisi Barat modern",
        legacy: "Penyair dan sufi terbesar",
        sumber_referensi: ["The Masnavi", "Essential Rumi"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Dalai Lama Tenzin Gyatso",
        deskripsi_tokoh: "Dalai Lama Tenzin Gyatso (lahir 1935) adalah pemimpin spiritual Buddhisme Tibet yang memenangkan Nobel Peace Prize untuk perjuangan perdamaian dan hak asasi manusia.",
        periode_hidup: "1935-Sekarang",
        negara_asal: "Tibet",
        bidang_keahlian: "Spiritualitas, Buddhisme, Hak Asasi",
        kontribusi_utama: "Buddhisme Tibet, Perjuangan Hak Asasi",
        pencapaian_penting: ["Pemimpin Spiritual", "Nobel Peace Prize", "Advokasi Hak Asasi"],
        pengaruh_sejarah: "Pemimpin spiritual dan advokat hak asasi global",
        legacy: "Pemimpin spiritual Buddhisme Tibet",
        sumber_referensi: ["My Land and My People", "The Art of Happiness"],
        kategori: "Tokoh Spiritual"
      },
      {
        nama_tokoh: "Alan Turing",
        deskripsi_tokoh: "Alan Turing (1912-1954) adalah matematikawan dan cryptographer Inggris yang mengembangkan konsep mesin Turing dan berkontribusi pada teori komputasi modern.",
        periode_hidup: "1912-1954",
        negara_asal: "Inggris",
        bidang_keahlian: "Matematika, Komputer",
        kontribusi_utama: "Mesin Turing, Teori Komputasi, AI",
        pencapaian_penting: ["Mesin Turing", "Turing Test", "Decryption Enigma"],
        pengaruh_sejarah: "Pendiri teori komputasi dan AI",
        legacy: "Bapak ilmu komputer teoritis",
        sumber_referensi: ["Computing Machinery and Intelligence", "Alan Turing Biography"],
        kategori: "Ilmuwan Komputer"
      }
    ];

    // Hapus data lama
    await Tokoh.deleteMany({});

    // Tambahkan data baru
    const hasilTambah = await Tokoh.insertMany(dataTokoh);

    console.log('Koneksi ke MongoDB Atlas berhasil');
    console.log('Data lama dihapus');
    console.log(`${hasilTambah.length} tokoh sejarah berhasil ditambahkan ke database`);
    
    // Tutup koneksi
    await mongoose.connection.close();
    console.log('Koneksi database ditutup');

  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}

// Jalankan fungsi
tambahDataTokoh();
